package main

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/yuin/goldmark"
)

//go:embed templates/CLAUDE.md templates/AGENTS.md
var skillTemplates embed.FS

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const (
	maxFileBytes    = 100 * 1024 // skip files larger than 100 KB
	maxFileLines    = 500        // truncate to 500 lines for LLM input
	apiURL          = "https://api.anthropic.com/v1/messages"
	llmModel        = "claude-haiku-4-5-20251001"
	apiVersion      = "2023-06-01"
	generatedTag    = "<!-- Generated by wikigen. Do not edit manually. -->"
	manifestFile    = ".wikigen-manifest.json"
	manifestVersion = 1
)

// Default directory exclusions (by base name).
var defaultExcludes = []string{".claude", ".codex", "docs"}

// Lock / generated data files to skip.
var skipFiles = map[string]bool{
	"pnpm-lock.yaml":    true,
	"package-lock.json": true,
	"go.sum":            true,
}

// Extension → language label.
var extLang = map[string]string{
	".go":    "Go",
	".swift": "Swift",
	".ts":    "TypeScript",
	".tsx":   "TypeScript",
	".js":    "JavaScript",
	".jsx":   "JavaScript",
	".c":     "C",
	".h":     "C",
	".py":    "Python",
	".sh":    "Shell",
	".yaml":  "YAML",
	".yml":   "YAML",
	".toml":  "TOML",
	".json":  "JSON",
}

// Special filename prefixes/exact matches that map to a language.
var specialFiles = map[string]string{
	"Makefile":   "Make",
	"Dockerfile": "Docker",
}

// Regex for rewriting file links in LLM output.
var linkPattern = regexp.MustCompile(`\[([^\]]+)\]\(\./([^)]+)\)`)

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type config struct {
	repoRoot          string
	wikiRoot          string
	excludes          map[string]bool
	baseURL           string
	dryRun            bool
	clean             bool
	full              bool
	jsonProgress      bool
	apiKey            string
	noDefaultExcludes bool
	noDepsGraph       bool
	noFileIndex       bool
	noRecipes         bool
	noTraces          bool
	noBoundaries      bool
	noTestHints       bool
	noSymbolIndex     bool
	noChurn           bool
}

type wikiArtifacts struct {
	depsEdgeCount int
	fileCount     int
	dirCount      int
	symbolCount   int
	hasChurn      bool
	hasRecipes    bool
	hasTraces     bool
}

type fileEntry struct {
	Name     string
	Language string
	Content  string
}

type dirBundle struct {
	Path           string
	Files          []fileEntry
	ChildSummaries []string
	ChildDirs      []string
}

// ---------------------------------------------------------------------------
// Manifest types
// ---------------------------------------------------------------------------

type manifestDirEntry struct {
	FilesHash   string            `json:"files_hash"`
	SummaryHash string            `json:"summary_hash"`
	Files       map[string]string `json:"files"`
}

type manifest struct {
	Version     int                         `json:"version"`
	Repo        string                      `json:"repo"`
	LastCommit  string                      `json:"last_commit"`
	GeneratedAt string                      `json:"generated_at"`
	Excludes    []string                    `json:"excludes"`
	Directories map[string]manifestDirEntry `json:"directories"`
}

// ---------------------------------------------------------------------------
// JSON progress event
// ---------------------------------------------------------------------------

type progressEvent struct {
	Event        string `json:"event"`
	Dir          string `json:"dir,omitempty"`
	Status       string `json:"status,omitempty"`
	FilesChanged int    `json:"files_changed,omitempty"`
	Message      string `json:"message,omitempty"`
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

func main() {
	cfg := parseArgs()

	if cfg.clean {
		doClean(cfg)
		return
	}

	if !cfg.dryRun && cfg.apiKey == "" {
		fmt.Fprintln(os.Stderr, "error: ANTHROPIC_API_KEY environment variable is not set")
		fmt.Fprintln(os.Stderr, "Set it or use --dry-run to test without API calls.")
		os.Exit(1)
	}

	// 1. Collect directories in post-order.
	dirs, err := collectDirs(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error walking directories: %v\n", err)
		os.Exit(1)
	}

	// 2. Load manifest and detect changes.
	oldManifest := loadManifest(cfg)
	forceFullScan := cfg.full || oldManifest == nil || oldManifest.Version != manifestVersion || !excludesMatch(oldManifest.Excludes, cfg.excludes)

	// Compute current hashes for all directories.
	currentHashes := computeAllHashes(cfg, dirs)

	// Determine dirty set.
	dirty := make(map[string]bool)
	if forceFullScan {
		for _, d := range dirs {
			dirty[d] = true
		}
		if !cfg.full && oldManifest != nil && oldManifest.Version != manifestVersion {
			emitProgress(cfg, progressEvent{Event: "info", Message: "Manifest version changed, forcing full scan"})
		}
		if !cfg.full && oldManifest != nil && !excludesMatch(oldManifest.Excludes, cfg.excludes) {
			emitProgress(cfg, progressEvent{Event: "info", Message: "Exclusion list changed, forcing full scan"})
		}
	} else {
		// Try git diff first, fall back to hash comparison.
		dirty = detectChangesGit(cfg, oldManifest, dirs)
		if dirty == nil {
			dirty = detectChangesHash(oldManifest, currentHashes, dirs)
		}
	}

	// Propagate dirty upward.
	propagateDirty(dirty, dirs)

	// Handle deleted directories.
	if oldManifest != nil {
		handleDeletedDirs(cfg, oldManifest, dirs, dirty)
	}

	// Check if anything needs work.
	dirtyCount := 0
	for _, d := range dirs {
		if dirty[d] {
			dirtyCount++
		}
	}
	if dirtyCount == 0 {
		emitProgress(cfg, progressEvent{Event: "done", Message: fmt.Sprintf("No changes detected (%d directories)", len(dirs))})
		os.Exit(0)
	}

	// 3. Create wiki output directory structure.
	if cfg.wikiRoot != cfg.repoRoot {
		os.MkdirAll(cfg.wikiRoot, 0755)
	}

	// Build parent→children map for child navigation in HTML.
	parentChildren := make(map[string][]string)
	for _, rel := range dirs {
		parent := filepath.Dir(rel)
		if parent == "." {
			parent = ""
		}
		parentChildren[parent] = append(parentChildren[parent], filepath.Base(rel))
	}
	for k := range parentChildren {
		sort.Strings(parentChildren[k])
	}

	// 4. Process directories: summarize dirty ones, load existing for clean ones.
	summaries := make(map[string]string)
	newManifest := &manifest{
		Version:     manifestVersion,
		Repo:        cfg.repoRoot,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Excludes:    sortedExcludes(cfg.excludes),
		Directories: make(map[string]manifestDirEntry),
	}

	regenCount := 0
	skipCount := 0
	failCount := 0

	for _, rel := range dirs {
		if !dirty[rel] {
			// Load existing summary from wiki folder.
			existing := loadExistingSummary(cfg, rel)
			if existing != "" {
				summaries[rel] = existing
			}
			// Carry forward manifest entry.
			if oldManifest != nil {
				if entry, ok := oldManifest.Directories[rel]; ok {
					newManifest.Directories[rel] = entry
				}
			}
			// Ensure HTML exists even for skipped directories.
			if existing != "" && !cfg.dryRun {
				htmlPath := filepath.Join(cfg.wikiRoot, rel, "SUMMARY.html")
				if _, err := os.Stat(htmlPath); os.IsNotExist(err) {
					writeHTMLPage(htmlPath, filepath.Base(rel), existing, rel, parentChildren[rel])
				}
			}
			emitProgress(cfg, progressEvent{Event: "skip", Dir: rel, Status: "unchanged"})
			skipCount++
			continue
		}

		bundle := buildBundle(cfg, rel, summaries)
		if len(bundle.Files) == 0 && len(bundle.ChildSummaries) == 0 {
			continue
		}

		nFiles := len(bundle.Files)
		nChildren := len(bundle.ChildSummaries)
		emitProgress(cfg, progressEvent{Event: "regenerate", Dir: rel, Status: "dirty", FilesChanged: nFiles})

		if !cfg.jsonProgress {
			fmt.Fprintf(os.Stderr, "Summarizing %s/ (%d files, %d children)...\n", rel, nFiles, nChildren)
		}

		if cfg.dryRun {
			summaries[rel] = fmt.Sprintf("(dry-run) %s: %d files, %d children", rel, nFiles, nChildren)
			continue
		}

		summary, err := summarize(cfg, bundle)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  warning: summarization failed for %s: %v\n", rel, err)
			summary = fmt.Sprintf("Summary generation failed for `%s`.", rel)
			failCount++
		}

		// Post-process links.
		summary = rewriteLinks(cfg, rel, summary)

		// Strip any leading H1 the LLM may have generated to avoid duplicates.
		summary = stripLeadingH1(summary)

		md := fmt.Sprintf("%s\n# %s\n\n%s\n", generatedTag, filepath.Base(rel), summary)
		summaries[rel] = md

		// Write SUMMARY.md to wiki folder.
		outDir := filepath.Join(cfg.wikiRoot, rel)
		os.MkdirAll(outDir, 0755)
		outPath := filepath.Join(outDir, "SUMMARY.md")
		if err := os.WriteFile(outPath, []byte(md), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
		}

		// Write SUMMARY.html alongside the markdown.
		htmlPath := filepath.Join(outDir, "SUMMARY.html")
		if err := writeHTMLPage(htmlPath, filepath.Base(rel), md, rel, parentChildren[rel]); err != nil {
			fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", htmlPath, err)
		}

		// Update manifest entry.
		if ch, ok := currentHashes[rel]; ok {
			ch.SummaryHash = hashString(md)
			newManifest.Directories[rel] = ch
		}
		regenCount++
	}

	// --- Sprint 005: Post-processing pipeline ---
	var artifacts wikiArtifacts
	artifacts.dirCount = len(dirs)

	if cfg.dryRun {
		// Print what would be generated.
		if !cfg.noDepsGraph {
			fmt.Fprintln(os.Stderr, "(dry-run) Would generate deps-graph.md")
		}
		if !cfg.noFileIndex {
			fmt.Fprintln(os.Stderr, "(dry-run) Would generate file-index.md")
		}
		if !cfg.noSymbolIndex {
			fmt.Fprintln(os.Stderr, "(dry-run) Would generate symbol-index.md")
		}
		if !cfg.noChurn {
			fmt.Fprintln(os.Stderr, "(dry-run) Would generate churn.md")
		}
		if !cfg.noRecipes {
			fmt.Fprintln(os.Stderr, "(dry-run) Would generate recipes.md (1 LLM call)")
		}
		if !cfg.noTraces {
			fmt.Fprintln(os.Stderr, "(dry-run) Would generate traces.md (1 LLM call)")
		}
	}

	if !cfg.dryRun {
		// Write dependency graph.
		if !cfg.noDepsGraph {
			edgeCount, err := writeDepsGraph(cfg, summaries)
			if err != nil {
				fmt.Fprintf(os.Stderr, "  warning: deps graph generation failed: %v\n", err)
			}
			artifacts.depsEdgeCount = edgeCount
		}

		// Write file index.
		if !cfg.noFileIndex {
			fileCount, err := writeFileIndex(cfg, dirs, summaries)
			if err != nil {
				fmt.Fprintf(os.Stderr, "  warning: file index generation failed: %v\n", err)
			}
			artifacts.fileCount = fileCount
		}

		// Write symbol index.
		if !cfg.noSymbolIndex {
			symbolCount, err := writeSymbolIndex(cfg, summaries)
			if err != nil {
				fmt.Fprintf(os.Stderr, "  warning: symbol index generation failed: %v\n", err)
			}
			artifacts.symbolCount = symbolCount
		}

		// Git analysis: churn.
		if !cfg.noChurn {
			churnData, _ := analyzeChurn(cfg.repoRoot)
			if len(churnData) > 0 {
				if err := writeChurn(cfg, churnData); err != nil {
					fmt.Fprintf(os.Stderr, "  warning: churn analysis failed: %v\n", err)
				}
				artifacts.hasChurn = true
			}
		}

		// Git analysis: co-change + recipes.
		if !cfg.noRecipes {
			clusters, _ := analyzeCoChanges(cfg.repoRoot)
			if len(clusters) > 0 {
				emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "Generating modification recipes"})
				if !cfg.jsonProgress {
					fmt.Fprintln(os.Stderr, "Generating modification recipes...")
				}
				recipesContent, err := generateRecipes(cfg, clusters, summaries)
				if err != nil {
					fmt.Fprintf(os.Stderr, "  warning: recipe generation failed: %v\n", err)
				} else if recipesContent != "" {
					writeRecipesFile(cfg, recipesContent)
					artifacts.hasRecipes = true
				}
			}
		}

		// Entry point traces.
		if !cfg.noTraces {
			emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "Generating entry point traces"})
			if !cfg.jsonProgress {
				fmt.Fprintln(os.Stderr, "Generating entry point traces...")
			}
			tracesContent, err := generateTraces(cfg, summaries)
			if err != nil {
				fmt.Fprintf(os.Stderr, "  warning: trace generation failed: %v\n", err)
			} else if tracesContent != "" {
				writeTracesFile(cfg, tracesContent)
				artifacts.hasTraces = true
			}
		}
	}

	// 5. Generate root overview and wiki.md.
	if !cfg.dryRun {
		// Collect top-level dirs for root overview.
		var topLevel []string
		for _, d := range dirs {
			if !strings.Contains(d, string(os.PathSeparator)) {
				topLevel = append(topLevel, d)
			}
		}
		sort.Strings(topLevel)

		emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "Generating project overview"})
		if !cfg.jsonProgress {
			fmt.Fprintln(os.Stderr, "Generating project overview...")
		}
		rootOverview, err := summarizeRoot(cfg.apiKey, topLevel, summaries)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  warning: root overview generation failed: %v\n", err)
			rootOverview = ""
		}

		emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "Generating wiki.md"})
		if !cfg.jsonProgress {
			fmt.Fprintln(os.Stderr, "Generating wiki.md...")
		}
		wiki := buildWiki(cfg, dirs, summaries, rootOverview, artifacts)
		wikiPath := filepath.Join(cfg.wikiRoot, "wiki.md")
		if err := os.WriteFile(wikiPath, []byte(wiki), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error writing wiki.md: %v\n", err)
			os.Exit(1)
		}

		// Write index.html alongside wiki.md.
		indexPath := filepath.Join(cfg.wikiRoot, "index.html")
		if err := writeHTMLPage(indexPath, "Codebase Wiki", wiki, "", parentChildren[""]); err != nil {
			fmt.Fprintf(os.Stderr, "error writing index.html: %v\n", err)
		}

		// Write LLM skill files (CLAUDE.md, AGENTS.md) into the wiki output.
		writeSkillFiles(cfg)
	} else {
		emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "(dry-run) Would write wiki.md"})
		if !cfg.jsonProgress {
			fmt.Fprintln(os.Stderr, "(dry-run) Would write wiki.md")
		}
	}

	// 6. Save manifest.
	if !cfg.dryRun {
		// Get current git HEAD.
		newManifest.LastCommit = getGitHead(cfg.repoRoot)
		saveManifest(cfg, newManifest)
	}

	// 7. Print stats.
	total := len(dirs)
	msg := fmt.Sprintf("Regenerated %d/%d directories (%d skipped)", regenCount, total, skipCount)
	if failCount > 0 {
		msg += fmt.Sprintf(", %d failed", failCount)
	}
	emitProgress(cfg, progressEvent{Event: "done", Message: msg})
	if !cfg.jsonProgress {
		fmt.Fprintln(os.Stderr, msg)
	}

	if failCount > 0 {
		os.Exit(2) // partial failure
	}
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

func parseArgs() config {
	cfg := config{
		excludes: make(map[string]bool),
	}
	var userExcludes []string
	args := os.Args[1:]

	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--dry-run":
			cfg.dryRun = true
		case a == "--clean":
			cfg.clean = true
		case a == "--full":
			cfg.full = true
		case a == "--json":
			cfg.jsonProgress = true
		case a == "--no-default-excludes":
			cfg.noDefaultExcludes = true
		case a == "--no-deps-graph":
			cfg.noDepsGraph = true
		case a == "--no-file-index":
			cfg.noFileIndex = true
		case a == "--no-recipes":
			cfg.noRecipes = true
		case a == "--no-traces":
			cfg.noTraces = true
		case a == "--no-boundaries":
			cfg.noBoundaries = true
		case a == "--no-test-hints":
			cfg.noTestHints = true
		case a == "--no-symbol-index":
			cfg.noSymbolIndex = true
		case a == "--no-churn":
			cfg.noChurn = true
		case a == "--help" || a == "-h":
			printUsage()
			os.Exit(0)
		case a == "--output" && i+1 < len(args):
			i++
			cfg.wikiRoot = args[i]
		case a == "--exclude" && i+1 < len(args):
			i++
			userExcludes = append(userExcludes, args[i])
		case a == "--base-url" && i+1 < len(args):
			i++
			cfg.baseURL = strings.TrimRight(args[i], "/")
		case strings.HasPrefix(a, "-"):
			fmt.Fprintf(os.Stderr, "unknown flag: %s\n", a)
			printUsage()
			os.Exit(1)
		default:
			cfg.repoRoot = a
		}
	}

	if cfg.repoRoot == "" {
		cfg.repoRoot = "."
	}
	cfg.repoRoot, _ = filepath.Abs(cfg.repoRoot)

	if cfg.wikiRoot == "" {
		cfg.wikiRoot = cfg.repoRoot
	} else {
		cfg.wikiRoot, _ = filepath.Abs(cfg.wikiRoot)
	}

	// Build exclusion set.
	cfg.excludes[".git"] = true // always exclude .git
	if !cfg.noDefaultExcludes {
		for _, d := range defaultExcludes {
			cfg.excludes[d] = true
		}
	}
	for _, d := range userExcludes {
		cfg.excludes[d] = true
	}

	cfg.apiKey = os.Getenv("ANTHROPIC_API_KEY")

	return cfg
}

func printUsage() {
	fmt.Fprintln(os.Stderr, `Usage: wikigen [flags] <repo>

Generates hierarchical markdown documentation for a codebase.

Flags:
  --output <dir>       Wiki output directory (default: in-place in repo)
  --exclude <pattern>  Exclude directory by base name (repeatable)
  --no-default-excludes  Clear default exclusions (only .git remains)
  --base-url <url>     URL prefix for source file links (e.g. https://github.com/org/repo/blob/main)
  --full               Force full regeneration (ignore manifest)
  --json               Emit line-delimited JSON progress events on stderr
  --dry-run            Show what would be summarized without calling the API
  --clean              Remove all generated files and manifest from wiki folder
  --no-deps-graph      Skip dependency graph generation (deps-graph.md)
  --no-file-index      Skip file index generation (file-index.md)
  --no-recipes         Skip modification recipes (recipes.md, saves 1 LLM call)
  --no-traces          Skip entry point traces (traces.md, saves 1 LLM call)
  --no-boundaries      Omit ## Boundary section from directory summaries
  --no-test-hints      Omit ## Testing section from directory summaries
  --no-symbol-index    Skip symbol index generation (symbol-index.md)
  --no-churn           Skip churn overlay generation (churn.md)
  --help               Show this help message`)
}

// ---------------------------------------------------------------------------
// Directory collection (post-order)
// ---------------------------------------------------------------------------

func collectDirs(cfg config) ([]string, error) {
	var dirs []string
	err := filepath.Walk(cfg.repoRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() {
			return nil
		}
		base := info.Name()
		if path != cfg.repoRoot && (strings.HasPrefix(base, ".") || cfg.excludes[base]) {
			return filepath.SkipDir
		}
		rel, _ := filepath.Rel(cfg.repoRoot, path)
		if rel == "." {
			return nil
		}
		dirs = append(dirs, rel)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(dirs, func(i, j int) bool {
		di := strings.Count(dirs[i], string(os.PathSeparator))
		dj := strings.Count(dirs[j], string(os.PathSeparator))
		if di != dj {
			return di > dj
		}
		return dirs[i] < dirs[j]
	})
	return dirs, nil
}

// ---------------------------------------------------------------------------
// Hashing
// ---------------------------------------------------------------------------

func hashBytes(data []byte) string {
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:])
}

func hashString(s string) string {
	return hashBytes([]byte(s))
}

func computeAllHashes(cfg config, dirs []string) map[string]manifestDirEntry {
	result := make(map[string]manifestDirEntry)
	for _, rel := range dirs {
		abs := filepath.Join(cfg.repoRoot, rel)
		entries, err := os.ReadDir(abs)
		if err != nil {
			continue
		}
		fileHashes := make(map[string]string)
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			name := e.Name()
			if !isEligibleFile(name) {
				continue
			}
			content, err := readFileContent(filepath.Join(abs, name))
			if err != nil || content == "" {
				continue
			}
			fileHashes[name] = hashString(content)
		}
		// Compute directory-level hash from sorted file hashes.
		var pairs []string
		for name, h := range fileHashes {
			pairs = append(pairs, name+":"+h)
		}
		sort.Strings(pairs)
		dirHash := hashString(strings.Join(pairs, "\n"))

		result[rel] = manifestDirEntry{
			FilesHash: dirHash,
			Files:     fileHashes,
		}
	}
	return result
}

// ---------------------------------------------------------------------------
// Manifest load/save
// ---------------------------------------------------------------------------

func loadManifest(cfg config) *manifest {
	path := filepath.Join(cfg.wikiRoot, manifestFile)
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		fmt.Fprintf(os.Stderr, "warning: corrupt manifest, will regenerate all: %v\n", err)
		return nil
	}
	return &m
}

func saveManifest(cfg config, m *manifest) {
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error marshaling manifest: %v\n", err)
		return
	}
	path := filepath.Join(cfg.wikiRoot, manifestFile)
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, data, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing manifest: %v\n", err)
		return
	}
	if err := os.Rename(tmpPath, path); err != nil {
		fmt.Fprintf(os.Stderr, "error renaming manifest: %v\n", err)
	}
}

func excludesMatch(a []string, b map[string]bool) bool {
	if len(a) != len(b) {
		return false
	}
	set := make(map[string]bool)
	for _, s := range a {
		set[s] = true
	}
	for k := range b {
		if !set[k] {
			return false
		}
	}
	return true
}

func sortedExcludes(m map[string]bool) []string {
	var s []string
	for k := range m {
		s = append(s, k)
	}
	sort.Strings(s)
	return s
}

// ---------------------------------------------------------------------------
// Change detection: git
// ---------------------------------------------------------------------------

func getGitHead(repoRoot string) string {
	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func isGitRepo(repoRoot string) bool {
	info, err := os.Stat(filepath.Join(repoRoot, ".git"))
	return err == nil && info.IsDir()
}

func detectChangesGit(cfg config, old *manifest, dirs []string) map[string]bool {
	if !isGitRepo(cfg.repoRoot) || old.LastCommit == "" {
		return nil // fall back to hash
	}

	currentHead := getGitHead(cfg.repoRoot)
	if currentHead == "" {
		return nil
	}
	if currentHead == old.LastCommit {
		// Same commit — no changes from git's perspective.
		// Still need to check for new/removed dirs via hash comparison.
		return detectChangesHash(old, computeAllHashes(cfg, dirs), dirs)
	}

	cmd := exec.Command("git", "diff", "--name-only", old.LastCommit, currentHead)
	cmd.Dir = cfg.repoRoot
	out, err := cmd.Output()
	if err != nil {
		emitProgress(cfg, progressEvent{Event: "info", Message: "git diff failed, falling back to hash comparison"})
		return nil
	}

	dirty := make(map[string]bool)
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	dirSet := make(map[string]bool)
	for _, d := range dirs {
		dirSet[d] = true
	}

	for _, line := range lines {
		if line == "" {
			continue
		}
		dir := filepath.Dir(line)
		// Walk up to find the first eligible directory.
		for dir != "." && dir != "" {
			if dirSet[dir] {
				dirty[dir] = true
				break
			}
			dir = filepath.Dir(dir)
		}
	}

	// Also check for new directories (not in manifest).
	for _, d := range dirs {
		if _, exists := old.Directories[d]; !exists {
			dirty[d] = true
		}
	}

	return dirty
}

// ---------------------------------------------------------------------------
// Change detection: hash fallback
// ---------------------------------------------------------------------------

func detectChangesHash(old *manifest, current map[string]manifestDirEntry, dirs []string) map[string]bool {
	dirty := make(map[string]bool)
	for _, d := range dirs {
		cur, hasCur := current[d]
		oldEntry, hasOld := old.Directories[d]
		if !hasOld {
			dirty[d] = true // new directory
			continue
		}
		if !hasCur {
			continue
		}
		if cur.FilesHash != oldEntry.FilesHash {
			dirty[d] = true
		}
	}
	return dirty
}

// ---------------------------------------------------------------------------
// Dirty propagation
// ---------------------------------------------------------------------------

func propagateDirty(dirty map[string]bool, dirs []string) {
	// Process in reverse (shallowest first) to propagate upward.
	for i := len(dirs) - 1; i >= 0; i-- {
		d := dirs[i]
		if !dirty[d] {
			continue
		}
		parent := filepath.Dir(d)
		for parent != "." && parent != "" {
			dirty[parent] = true
			parent = filepath.Dir(parent)
		}
	}
}

// ---------------------------------------------------------------------------
// Deleted directory handling
// ---------------------------------------------------------------------------

func handleDeletedDirs(cfg config, old *manifest, dirs []string, dirty map[string]bool) {
	currentSet := make(map[string]bool)
	for _, d := range dirs {
		currentSet[d] = true
	}
	for d := range old.Directories {
		if !currentSet[d] {
			// Directory was removed from repo.
			summaryPath := filepath.Join(cfg.wikiRoot, d, "SUMMARY.md")
			if err := os.Remove(summaryPath); err == nil {
				emitProgress(cfg, progressEvent{Event: "delete", Dir: d, Message: "Removed deleted directory summary"})
			}
			// Mark parent as dirty.
			parent := filepath.Dir(d)
			if parent != "." {
				dirty[parent] = true
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Bundle building
// ---------------------------------------------------------------------------

func buildBundle(cfg config, rel string, summaries map[string]string) dirBundle {
	abs := filepath.Join(cfg.repoRoot, rel)
	entries, _ := os.ReadDir(abs)

	b := dirBundle{Path: rel}

	for _, e := range entries {
		if e.IsDir() {
			childRel := filepath.Join(rel, e.Name())
			if s, ok := summaries[childRel]; ok {
				b.ChildSummaries = append(b.ChildSummaries, s)
				b.ChildDirs = append(b.ChildDirs, e.Name())
			}
			continue
		}
		name := e.Name()
		if !isEligibleFile(name) {
			continue
		}
		lang := detectLanguage(name)
		if lang == "" {
			continue
		}
		content, err := readFileContent(filepath.Join(abs, name))
		if err != nil || content == "" {
			continue
		}
		b.Files = append(b.Files, fileEntry{Name: name, Language: lang, Content: content})
	}
	sort.Slice(b.Files, func(i, j int) bool {
		return b.Files[i].Name < b.Files[j].Name
	})
	return b
}

func isEligibleFile(name string) bool {
	if skipFiles[name] || name == "SUMMARY.md" || name == manifestFile {
		return false
	}
	if detectLanguage(name) == "" {
		return false
	}
	return true
}

func detectLanguage(name string) string {
	for prefix, lang := range specialFiles {
		if name == prefix || strings.HasPrefix(name, prefix+".") {
			return lang
		}
	}
	ext := filepath.Ext(name)
	return extLang[ext]
}

func readFileContent(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return "", err
	}
	if info.Size() > maxFileBytes {
		return "", nil
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}

	check := data
	if len(check) > 512 {
		check = check[:512]
	}
	if bytes.ContainsRune(check, 0) {
		return "", nil
	}

	header := string(check)
	if strings.Contains(header, "Code generated") || strings.Contains(header, "DO NOT EDIT") {
		return "", nil
	}

	lines := strings.SplitN(string(data), "\n", maxFileLines+1)
	if len(lines) > maxFileLines {
		lines = lines[:maxFileLines]
		lines = append(lines, fmt.Sprintf("\n... (truncated at %d lines)", maxFileLines))
	}
	return strings.Join(lines, "\n"), nil
}

// ---------------------------------------------------------------------------
// Load existing summary from wiki folder
// ---------------------------------------------------------------------------

func loadExistingSummary(cfg config, rel string) string {
	path := filepath.Join(cfg.wikiRoot, rel, "SUMMARY.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

// ---------------------------------------------------------------------------
// Claude API summarization
// ---------------------------------------------------------------------------

type apiMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type apiRequest struct {
	Model     string       `json:"model"`
	MaxTokens int          `json:"max_tokens"`
	System    string       `json:"system"`
	Messages  []apiMessage `json:"messages"`
}

type apiContentBlock struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

type apiResponse struct {
	Content []apiContentBlock `json:"content"`
	Error   *struct {
		Message string `json:"message"`
	} `json:"error"`
}

func callLLM(apiKey, systemPrompt, userPrompt string) (string, error) {
	reqBody := apiRequest{
		Model:     llmModel,
		MaxTokens: 2048,
		System:    systemPrompt,
		Messages: []apiMessage{
			{Role: "user", Content: userPrompt},
		},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequest("POST", apiURL, bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", apiVersion)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("API call failed: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("API returned %d: %s", resp.StatusCode, string(respBody))
	}
	var apiResp apiResponse
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if apiResp.Error != nil {
		return "", fmt.Errorf("API error: %s", apiResp.Error.Message)
	}
	var texts []string
	for _, block := range apiResp.Content {
		if block.Type == "text" {
			texts = append(texts, block.Text)
		}
	}
	return strings.Join(texts, "\n"), nil
}

func summarize(cfg config, b dirBundle) (string, error) {
	prompt := buildPrompt(b)

	var sysPrompt strings.Builder
	sysPrompt.WriteString(`You are writing documentation for an LLM that will use this wiki to understand and modify a codebase. The LLM reads the wiki top-down, so each summary must help it both navigate (which files to open) and comprehend (how things work and connect) without reading every source file.

Write a markdown summary following this structure:

## Overview
1-3 sentences: What this directory is responsible for. State its role in the larger system.

## Key files
Bullet list with relative links and one-line descriptions:
- [filename](./filename) — description

## How it works
Explain the internal data flow and control flow. How do the files in this directory interact? What are the key call chains? If there is a primary entry point, start there and trace the flow. For example: "Requests arrive at handler.go, which validates input using validator.go, then calls store.go to persist. Errors are wrapped by errors.go and returned as HTTP responses."

## Key types and interfaces
List the most important exported types, functions, and interfaces. For interfaces, note who implements them. For key functions, note who calls them and what they return. Group related items rather than listing everything flat.

## Dependencies
Which other packages/directories does this code import from or get called by? List the most important ones with a brief note on the relationship:
- Imports: "policy/ for PolicySet, cedar/ for Compile()"
- Imported by: "runner/ calls LSMManager.Load(), leashd/ calls UpdateRuntimeRules()"

If you can determine this from the code, include it. If you cannot determine the full picture, list what you can see from imports and function signatures.

`)

	if !cfg.noBoundaries {
		sysPrompt.WriteString(`## Boundary
State whether this directory is: **public** (exported API, meant to be imported by other packages), **internal** (implementation detail, not meant for direct external use), or **entry point** (binary/command, not imported). One sentence on what the contract is — what callers can rely on.

`)
	}

	if !cfg.noTestHints {
		sysPrompt.WriteString(`## Testing
Where tests live (colocated _test.go files, separate tests/ directory, or __tests__/). Note the testing pattern: table-driven, fixtures, mocks, integration vs unit. If there are test helpers or shared fixtures, name them. Skip this section if there are no tests in this directory.

`)
	}

	sysPrompt.WriteString(`## Configuration
Note any environment variables, config files, CLI flags, or constants that control behavior in this directory. Skip this section if there are none.

## When to look here
Bullet list of task descriptions that would lead an LLM to this directory. Be specific to what the code actually does. For example: "Modifying how Cedar policies are parsed", "Adding a new CLI subcommand", "Changing container network rules".

## Child directories
(If any) For each child, a bullet with a description of what it owns and what tasks would require looking there.

Guidelines:
- Be concise but not shallow. Prioritize understanding over brevity.
- Do not invent functionality not present in the code.
- Use relative file links for files in this directory.
- Omit any section that has no meaningful content (e.g., skip Configuration if there are no config knobs).`)

	return callLLM(cfg.apiKey, sysPrompt.String(), prompt)
}

func buildPrompt(b dirBundle) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Directory: `%s`\n\n", b.Path))

	if len(b.Files) > 0 {
		sb.WriteString("## Source files in this directory\n\n")
		for _, f := range b.Files {
			sb.WriteString(fmt.Sprintf("### %s (%s)\n```%s\n%s\n```\n\n", f.Name, f.Language, strings.ToLower(f.Language), f.Content))
		}
	}

	if len(b.ChildSummaries) > 0 {
		sb.WriteString("## Child directory summaries\n\n")
		for i, cs := range b.ChildSummaries {
			if i < len(b.ChildDirs) {
				sb.WriteString(fmt.Sprintf("### Child: %s/\n%s\n\n", b.ChildDirs[i], cs))
			}
		}
	}

	return sb.String()
}

// ---------------------------------------------------------------------------
// Link rewriting
// ---------------------------------------------------------------------------

func rewriteLinks(cfg config, dirRel string, summary string) string {
	if cfg.baseURL != "" {
		return linkPattern.ReplaceAllStringFunc(summary, func(match string) string {
			parts := linkPattern.FindStringSubmatch(match)
			if len(parts) != 3 {
				return match
			}
			label, file := parts[1], parts[2]
			return fmt.Sprintf("[%s](%s/%s/%s)", label, cfg.baseURL, dirRel, file)
		})
	}
	// No base URL: replace links with inline code.
	return linkPattern.ReplaceAllStringFunc(summary, func(match string) string {
		parts := linkPattern.FindStringSubmatch(match)
		if len(parts) != 3 {
			return match
		}
		return "`" + parts[1] + "`"
	})
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// stripLeadingH1 removes a leading "# ..." line from LLM output so we don't
// duplicate the header we add ourselves.
func stripLeadingH1(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "# ") {
		if idx := strings.Index(s, "\n"); idx >= 0 {
			return strings.TrimSpace(s[idx+1:])
		}
		return "" // entire string was a single H1
	}
	return s
}

// extractFirstSentence pulls the first non-empty, non-heading line from a
// summary and returns it (stripped of markdown formatting) as a one-line
// description suitable for a table-of-contents entry.
func extractFirstSentence(summary string) string {
	for _, line := range strings.Split(summary, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "<!--") || strings.HasPrefix(line, "---") {
			continue
		}
		// Strip bold/italic markers and leading list markers.
		line = strings.TrimLeft(line, "- *_")
		line = strings.TrimRight(line, " *_")
		// Truncate at first period if present.
		if idx := strings.Index(line, ". "); idx > 0 && idx < 200 {
			line = line[:idx+1]
		}
		if len(line) > 200 {
			line = line[:197] + "..."
		}
		return line
	}
	return ""
}

// ---------------------------------------------------------------------------
// HTML generation
// ---------------------------------------------------------------------------

var htmlTemplate = template.Must(template.New("page").Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}}</title>
<style>
  :root { --bg: #fff; --fg: #1a1a1a; --muted: #6b7280; --border: #e5e7eb; --link: #2563eb; --code-bg: #f3f4f6; --nav-bg: #f9fafb; }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #111; --fg: #e5e5e5; --muted: #9ca3af; --border: #333; --link: #60a5fa; --code-bg: #1e1e1e; --nav-bg: #1a1a1a; }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg); color: var(--fg); line-height: 1.6; max-width: 52rem; margin: 0 auto; padding: 2rem 1.5rem; }
  nav.breadcrumb { font-size: 0.85rem; color: var(--muted); margin-bottom: 1.5rem; padding: 0.5rem 0.75rem; background: var(--nav-bg); border-radius: 6px; }
  nav.breadcrumb a { color: var(--link); text-decoration: none; }
  nav.breadcrumb a:hover { text-decoration: underline; }
  h1 { font-size: 1.75rem; margin-bottom: 1rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }
  h2 { font-size: 1.35rem; margin-top: 2rem; margin-bottom: 0.75rem; }
  h3 { font-size: 1.1rem; margin-top: 1.5rem; margin-bottom: 0.5rem; }
  p { margin-bottom: 0.75rem; }
  a { color: var(--link); text-decoration: none; }
  a:hover { text-decoration: underline; }
  ul, ol { margin: 0.5rem 0 1rem 1.5rem; }
  li { margin-bottom: 0.25rem; }
  code { font-family: "SF Mono", "Fira Code", Menlo, monospace; font-size: 0.88em; background: var(--code-bg); padding: 0.15em 0.35em; border-radius: 4px; }
  pre { background: var(--code-bg); padding: 1rem; border-radius: 6px; overflow-x: auto; margin: 1rem 0; }
  pre code { background: none; padding: 0; font-size: 0.85em; }
  hr { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
  strong { font-weight: 600; }
  nav.children { font-size: 0.85rem; color: var(--muted); margin-top: 2rem; padding: 0.5rem 0.75rem; background: var(--nav-bg); border-radius: 6px; }
  nav.children a { color: var(--link); text-decoration: none; margin: 0 0.25rem; }
  nav.children a:hover { text-decoration: underline; }
  .generated { font-size: 0.75rem; color: var(--muted); text-align: center; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); }
</style>
</head>
<body>
{{if .Breadcrumb}}<nav class="breadcrumb">{{.Breadcrumb}}</nav>{{end}}
{{.Body}}
{{if .ChildNav}}{{.ChildNav}}{{end}}
<div class="generated">Generated by wikigen</div>
</body>
</html>
`))

type htmlPage struct {
	Title      string
	Breadcrumb template.HTML
	Body       template.HTML
	ChildNav   template.HTML
}

// markdownToHTML converts markdown text to an HTML body fragment.
func markdownToHTML(md string) string {
	// Strip the wikigen comment tag before converting.
	md = strings.ReplaceAll(md, generatedTag, "")
	var buf bytes.Buffer
	if err := goldmark.Convert([]byte(md), &buf); err != nil {
		return "<p>Error rendering markdown.</p>"
	}
	return buf.String()
}

// rewriteMDLinksToHTML rewrites .md hrefs to .html in the HTML output so
// navigation works in a browser.
var mdLinkInHTML = regexp.MustCompile(`href="([^"]*?)\.md"`)

func rewriteHTMLLinks(html string) string {
	return mdLinkInHTML.ReplaceAllString(html, `href="$1.html"`)
}

// buildBreadcrumb creates an HTML breadcrumb trail for a directory path.
// rel is relative to the wiki root (e.g., "internal/lsm").
func buildBreadcrumb(rel string) template.HTML {
	if rel == "" || rel == "." {
		return ""
	}
	parts := strings.Split(rel, string(os.PathSeparator))
	var crumbs []string
	// Link to root wiki.
	depth := len(parts)
	rootHref := strings.Repeat("../", depth) + "index.html"
	crumbs = append(crumbs, fmt.Sprintf(`<a href="%s">Wiki</a>`, rootHref))
	// Intermediate dirs.
	for i, p := range parts {
		if i == len(parts)-1 {
			crumbs = append(crumbs, p)
		} else {
			ups := len(parts) - i - 1
			href := strings.Repeat("../", ups) + "SUMMARY.html"
			crumbs = append(crumbs, fmt.Sprintf(`<a href="%s">%s</a>`, href, p))
		}
	}
	return template.HTML(strings.Join(crumbs, " / "))
}

// buildChildNav creates an HTML nav element linking to child directory summaries.
func buildChildNav(childDirs []string) template.HTML {
	if len(childDirs) == 0 {
		return ""
	}
	var links []string
	for _, child := range childDirs {
		links = append(links, fmt.Sprintf(`<a href="%s/SUMMARY.html">%s/</a>`, child, child))
	}
	return template.HTML(fmt.Sprintf(`<nav class="children"><strong>Child directories:</strong> %s</nav>`, strings.Join(links, " &middot; ")))
}

// writeHTMLPage renders a markdown string as a styled HTML page.
func writeHTMLPage(outPath, title, mdContent, rel string, childDirs []string) error {
	body := markdownToHTML(mdContent)
	body = rewriteHTMLLinks(body)

	page := htmlPage{
		Title:      title + " — Codebase Wiki",
		Breadcrumb: buildBreadcrumb(rel),
		Body:       template.HTML(body),
		ChildNav:   buildChildNav(childDirs),
	}

	var buf bytes.Buffer
	if err := htmlTemplate.Execute(&buf, page); err != nil {
		return fmt.Errorf("render HTML template: %w", err)
	}
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

// ---------------------------------------------------------------------------
// Summary parsing engine
// ---------------------------------------------------------------------------

type depEdge struct {
	Dir  string
	Note string
}

type fileIndexEntry struct {
	Name string
	Dir  string
	Desc string
	Lang string
}

type symbolEntry struct {
	Name     string
	Kind     string
	Location string
	Dir      string
}

func extractSection(summary, heading string) string {
	marker := "## " + heading
	idx := strings.Index(summary, marker)
	if idx < 0 {
		return ""
	}
	start := idx + len(marker)
	if nl := strings.Index(summary[start:], "\n"); nl >= 0 {
		start += nl + 1
	} else {
		return ""
	}
	rest := summary[start:]
	end := strings.Index(rest, "\n## ")
	if end >= 0 {
		return strings.TrimSpace(rest[:end])
	}
	return strings.TrimSpace(rest)
}

func parseDependencies(summary, dir string) (imports []depEdge, importedBy []depEdge) {
	section := extractSection(summary, "Dependencies")
	if section == "" {
		return
	}
	for _, line := range strings.Split(section, "\n") {
		line = strings.TrimSpace(line)
		line = strings.TrimPrefix(line, "- ")
		line = strings.TrimPrefix(line, "* ")
		lower := strings.ToLower(line)
		if strings.HasPrefix(lower, "imports:") || strings.HasPrefix(lower, "imports ") {
			note := strings.TrimSpace(line[len("imports"):])
			note = strings.TrimPrefix(note, ":")
			note = strings.TrimSpace(note)
			imports = append(imports, depEdge{Dir: dir, Note: note})
		} else if strings.HasPrefix(lower, "imported by:") || strings.HasPrefix(lower, "imported by ") {
			note := strings.TrimSpace(line[len("imported by"):])
			note = strings.TrimPrefix(note, ":")
			note = strings.TrimSpace(note)
			importedBy = append(importedBy, depEdge{Dir: dir, Note: note})
		}
	}
	return
}

var keyFilePattern = regexp.MustCompile(`\[([^\]]+)\]\(\./([^)]+)\)\s*[-—]\s*(.+)`)

func parseKeyFiles(summary, dir string) []fileIndexEntry {
	section := extractSection(summary, "Key files")
	if section == "" {
		return nil
	}
	var results []fileIndexEntry
	for _, line := range strings.Split(section, "\n") {
		m := keyFilePattern.FindStringSubmatch(line)
		if m != nil {
			results = append(results, fileIndexEntry{
				Name: m[1],
				Dir:  dir,
				Desc: strings.TrimSpace(m[3]),
			})
		}
	}
	return results
}

func parseSymbols(summary, dir string) []symbolEntry {
	section := extractSection(summary, "Key types and interfaces")
	if section == "" {
		return nil
	}
	var results []symbolEntry
	for _, line := range strings.Split(section, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || (!strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "*")) {
			continue
		}
		line = strings.TrimPrefix(line, "- ")
		line = strings.TrimPrefix(line, "* ")
		entry := symbolEntry{Dir: dir}
		if idx := strings.Index(line, "`"); idx >= 0 {
			end := strings.Index(line[idx+1:], "`")
			if end >= 0 {
				name := line[idx+1 : idx+1+end]
				entry.Name = name
				lower := strings.ToLower(line)
				switch {
				case strings.Contains(lower, "interface"):
					entry.Kind = "interface"
				case strings.Contains(lower, "struct") || strings.Contains(lower, "type"):
					entry.Kind = "type"
				case strings.Contains(name, "("):
					entry.Kind = "func"
				default:
					entry.Kind = "type"
				}
				// Try to find file reference like "in `filename.go`" or "(filename.go)".
				entry.Location = dir + "/"
				restOfLine := line[idx+1+end+1:]
				if fIdx := strings.Index(restOfLine, "`"); fIdx >= 0 {
					fEnd := strings.Index(restOfLine[fIdx+1:], "`")
					if fEnd >= 0 {
						ref := restOfLine[fIdx+1 : fIdx+1+fEnd]
						if strings.Contains(ref, ".") && !strings.Contains(ref, " ") {
							entry.Location = dir + "/" + ref
						}
					}
				}
				results = append(results, entry)
			}
		}
	}
	return results
}

func parseBoundary(summary string) string {
	section := extractSection(summary, "Boundary")
	if section == "" {
		return ""
	}
	lower := strings.ToLower(section)
	switch {
	case strings.Contains(lower, "entry point"):
		return "entry point"
	case strings.Contains(lower, "public"):
		return "public"
	case strings.Contains(lower, "internal"):
		return "internal"
	default:
		return ""
	}
}

// ---------------------------------------------------------------------------
// Git analysis
// ---------------------------------------------------------------------------

type coChangeCluster struct {
	Files []string
	Count int
}

type churnEntry struct {
	Dir   string
	Count int
	Level string
}

func analyzeCoChanges(repoRoot string) ([]coChangeCluster, error) {
	if _, err := os.Stat(filepath.Join(repoRoot, ".git")); err != nil {
		return nil, nil
	}
	cmd := exec.Command("git", "-C", repoRoot, "log", "--pretty=format:%H", "--since=1y", "-500")
	out, err := cmd.Output()
	if err != nil {
		return nil, nil
	}
	hashes := strings.Split(strings.TrimSpace(string(out)), "\n")
	if len(hashes) < 50 {
		return nil, nil
	}

	type filePair struct{ a, b string }
	pairCount := make(map[filePair]int)

	for _, hash := range hashes {
		cmd := exec.Command("git", "-C", repoRoot, "diff-tree", "--no-commit-id", "--name-only", "-r", hash)
		out, err := cmd.Output()
		if err != nil {
			continue
		}
		var eligible []string
		for _, f := range strings.Split(strings.TrimSpace(string(out)), "\n") {
			if f != "" && detectLanguage(filepath.Base(f)) != "" {
				eligible = append(eligible, f)
			}
		}
		for i := 0; i < len(eligible); i++ {
			for j := i + 1; j < len(eligible); j++ {
				a, b := eligible[i], eligible[j]
				if a > b {
					a, b = b, a
				}
				pairCount[filePair{a, b}]++
			}
		}
	}

	type scoredPair struct {
		a, b  string
		count int
	}
	var pairs []scoredPair
	for p, c := range pairCount {
		if c >= 3 {
			pairs = append(pairs, scoredPair{p.a, p.b, c})
		}
	}
	sort.Slice(pairs, func(i, j int) bool {
		return pairs[i].count > pairs[j].count
	})

	used := make(map[string]bool)
	var clusters []coChangeCluster
	for _, p := range pairs {
		if used[p.a] || used[p.b] {
			continue
		}
		cluster := coChangeCluster{Files: []string{p.a, p.b}, Count: p.count}
		used[p.a] = true
		used[p.b] = true
		for _, p2 := range pairs {
			if len(cluster.Files) >= 8 {
				break
			}
			candidate := ""
			if !used[p2.a] && used[p2.b] {
				candidate = p2.a
			} else if used[p2.a] && !used[p2.b] {
				candidate = p2.b
			}
			if candidate == "" {
				continue
			}
			fits := true
			for _, existing := range cluster.Files {
				a, b := candidate, existing
				if a > b {
					a, b = b, a
				}
				if pairCount[filePair{a, b}] < 3 {
					fits = false
					break
				}
			}
			if fits {
				cluster.Files = append(cluster.Files, candidate)
				used[candidate] = true
			}
		}
		clusters = append(clusters, cluster)
		if len(clusters) >= 15 {
			break
		}
	}
	return clusters, nil
}

func analyzeChurn(repoRoot string) ([]churnEntry, error) {
	if _, err := os.Stat(filepath.Join(repoRoot, ".git")); err != nil {
		return nil, nil
	}
	// Check we have at least 30 days of history.
	firstCmd := exec.Command("git", "-C", repoRoot, "log", "--since=30d", "--oneline", "-1")
	firstOut, err := firstCmd.Output()
	if err != nil || strings.TrimSpace(string(firstOut)) == "" {
		return nil, nil // not enough history
	}

	cmd := exec.Command("git", "-C", repoRoot, "log", "--since=90d", "--name-only", "--pretty=format:")
	out, err := cmd.Output()
	if err != nil {
		return nil, nil
	}
	dirCount := make(map[string]int)
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		dir := filepath.Dir(line)
		if dir == "." {
			continue
		}
		parts := strings.SplitN(dir, string(os.PathSeparator), 3)
		if len(parts) >= 2 {
			dir = filepath.Join(parts[0], parts[1])
		} else {
			dir = parts[0]
		}
		dirCount[dir]++
	}
	if len(dirCount) == 0 {
		return nil, nil
	}
	var entries []churnEntry
	for dir, count := range dirCount {
		entries = append(entries, churnEntry{Dir: dir, Count: count})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Count > entries[j].Count
	})
	for i := range entries {
		pct := float64(i) / float64(len(entries))
		switch {
		case pct < 0.2:
			entries[i].Level = "high"
		case pct >= 0.6:
			entries[i].Level = "low"
		default:
			entries[i].Level = "medium"
		}
	}
	return entries, nil
}

// ---------------------------------------------------------------------------
// Root-level project summary
// ---------------------------------------------------------------------------

func summarizeRoot(apiKey string, topDirs []string, summaries map[string]string) (string, error) {
	var sb strings.Builder
	sb.WriteString("Generate a project-level overview for an LLM that will use this wiki to navigate the codebase.\n\n")
	sb.WriteString("## Top-level directory summaries\n\n")
	for _, d := range topDirs {
		if s, ok := summaries[d]; ok {
			sb.WriteString(fmt.Sprintf("### %s/\n%s\n\n", d, s))
		}
	}

	return callLLM(apiKey,
		`You are writing the root page of a codebase wiki that an LLM will use to understand and navigate code for tasks.

Given summaries of all top-level directories, produce:

## Project overview
2-3 sentences: What the project is, what problem it solves, and who uses it.

## Architecture
How the major pieces connect. Describe the key data flows end-to-end. For example: "User invokes the CLI (cmd/), which starts a daemon (internal/leashd/) that loads Cedar policies (internal/policy/) and enforces them via eBPF (internal/lsm/). The control UI (controlui/) connects over WebSocket to show real-time events." Cover 2-3 primary flows, not every package.

## Key concepts
Define 3-5 domain-specific terms or concepts that appear throughout the codebase and that an LLM needs to understand before reading the code. For example: "Cedar policy", "LSM rule", "transpiler", "MCP observability". One sentence each.

## Navigation guide
A bullet list mapping task categories to specific directories. Be specific — list the exact directories, not just top-level ones. For example:
- "To modify CLI commands → cmd/leash/"
- "To change kernel-level policy enforcement → internal/lsm/, internal/transpiler/"
- "To update the web UI → controlui/web/src/"
- "To change how policies are parsed and watched → internal/policy/, internal/cedar/"

Cover at least 10 common task categories.

Be specific and accurate. Do not add a Contents listing — that will be generated separately.`,
		sb.String())
}

// ---------------------------------------------------------------------------
// Recipe and trace generation
// ---------------------------------------------------------------------------

func generateRecipes(cfg config, clusters []coChangeCluster, summaries map[string]string) (string, error) {
	if len(clusters) == 0 {
		return "", nil
	}
	var sb strings.Builder
	sb.WriteString("## Co-change clusters from git history\n\n")
	for i, c := range clusters {
		sb.WriteString(fmt.Sprintf("### Cluster %d (co-occurred in %d+ commits)\n", i+1, c.Count))
		for _, f := range c.Files {
			sb.WriteString(fmt.Sprintf("- `%s`\n", f))
		}
		sb.WriteString("\n")
	}
	sb.WriteString("## Directory summaries (for context)\n\n")
	for dir, summary := range summaries {
		overview := extractSection(summary, "Overview")
		if overview != "" {
			sb.WriteString(fmt.Sprintf("### %s/\n%s\n\n", dir, overview))
		}
	}
	return callLLM(cfg.apiKey,
		`You are writing modification recipes for a codebase wiki. Given file co-change clusters from git history and directory summaries, produce 10-15 modification recipes.

Each recipe should have:
1. A descriptive name as an H2 heading (e.g., "## Add a new API endpoint")
2. A bullet list of the files involved, with a one-line note per file on what to change there
3. Use relative paths from the repo root

Focus on the most common and useful modification patterns. Name recipes after the task ("Add a new ...", "Change how ...", "Fix ..."), not the files.

Output markdown only. No preamble.`,
		sb.String())
}

func generateTraces(cfg config, summaries map[string]string) (string, error) {
	var sb strings.Builder
	sb.WriteString("## Directory summaries\n\n")
	for dir, summary := range summaries {
		overview := extractSection(summary, "Overview")
		howItWorks := extractSection(summary, "How it works")
		keyFiles := extractSection(summary, "Key files")
		if overview != "" {
			sb.WriteString(fmt.Sprintf("### %s/\n%s\n\n", dir, overview))
		}
		if howItWorks != "" {
			sb.WriteString("**How it works:** " + howItWorks + "\n\n")
		}
		if keyFiles != "" {
			sb.WriteString("**Key files:**\n" + keyFiles + "\n\n")
		}
	}
	return callLLM(cfg.apiKey,
		`You are writing entry point traces for a codebase wiki. Given directory summaries, identify the 2-3 most important entry points (main() functions, HTTP server bootstrap, CLI command dispatch, event listeners) and trace their execution end-to-end through the codebase.

For each trace:
1. Use an H2 heading with the trace name (e.g., "## HTTP request → response")
2. Walk through the flow step by step, naming specific files and functions at each step
3. Use → arrows to show the flow direction
4. Keep it concrete — name actual files, not abstract concepts

Output markdown only. No preamble.`,
		sb.String())
}

// ---------------------------------------------------------------------------
// Root artifact writers
// ---------------------------------------------------------------------------

func writeDepsGraph(cfg config, summaries map[string]string) (int, error) {
	boundaries := make(map[string]string)
	for dir, summary := range summaries {
		if b := parseBoundary(summary); b != "" {
			boundaries[dir] = b
		}
	}
	var dirs []string
	for dir := range summaries {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	var sb strings.Builder
	sb.WriteString(generatedTag + "\n")
	sb.WriteString("# Dependency Graph\n\nDirectory-to-directory dependencies extracted from summaries.\n\n")
	sb.WriteString("```\n")
	edgeCount := 0
	for _, dir := range dirs {
		imports, _ := parseDependencies(summaries[dir], dir)
		if len(imports) == 0 {
			continue
		}
		label := dir
		if b, ok := boundaries[dir]; ok {
			label = fmt.Sprintf("%s (%s)", dir, b)
		}
		// Combine all import notes into one line.
		var notes []string
		for _, imp := range imports {
			notes = append(notes, imp.Note)
		}
		sb.WriteString(fmt.Sprintf("%s → %s\n", label, strings.Join(notes, ", ")))
		edgeCount += len(imports)
	}
	sb.WriteString("```\n")
	md := sb.String()
	if err := os.WriteFile(filepath.Join(cfg.wikiRoot, "deps-graph.md"), []byte(md), 0644); err != nil {
		return 0, err
	}
	return edgeCount, writeHTMLPage(filepath.Join(cfg.wikiRoot, "deps-graph.html"), "Dependency Graph", md, "", nil)
}

func writeFileIndex(cfg config, dirs []string, summaries map[string]string) (int, error) {
	descMap := make(map[string]map[string]string)
	for dir, summary := range summaries {
		for _, fe := range parseKeyFiles(summary, dir) {
			if descMap[dir] == nil {
				descMap[dir] = make(map[string]string)
			}
			descMap[dir][fe.Name] = fe.Desc
		}
	}
	var entries []fileIndexEntry
	for _, rel := range dirs {
		abs := filepath.Join(cfg.repoRoot, rel)
		dirEntries, err := os.ReadDir(abs)
		if err != nil {
			continue
		}
		for _, e := range dirEntries {
			if e.IsDir() {
				continue
			}
			name := e.Name()
			lang := detectLanguage(name)
			if lang == "" {
				continue
			}
			desc := ""
			if dm, ok := descMap[rel]; ok {
				desc = dm[name]
			}
			entries = append(entries, fileIndexEntry{Name: name, Dir: rel, Desc: desc, Lang: lang})
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name != entries[j].Name {
			return entries[i].Name < entries[j].Name
		}
		return entries[i].Dir < entries[j].Dir
	})
	var sb strings.Builder
	sb.WriteString(generatedTag + "\n")
	sb.WriteString(fmt.Sprintf("# File Index\n\n%d source files across %d directories.\n\n", len(entries), len(dirs)))
	sb.WriteString("| File | Directory | Language | Description |\n")
	sb.WriteString("|------|-----------|----------|-------------|\n")
	for _, e := range entries {
		desc := e.Desc
		if desc == "" {
			desc = "—"
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", e.Name, e.Dir, e.Lang, desc))
	}
	md := sb.String()
	if err := os.WriteFile(filepath.Join(cfg.wikiRoot, "file-index.md"), []byte(md), 0644); err != nil {
		return 0, err
	}
	return len(entries), writeHTMLPage(filepath.Join(cfg.wikiRoot, "file-index.html"), "File Index", md, "", nil)
}

func writeSymbolIndex(cfg config, summaries map[string]string) (int, error) {
	var allSymbols []symbolEntry
	for dir, summary := range summaries {
		allSymbols = append(allSymbols, parseSymbols(summary, dir)...)
	}
	sort.Slice(allSymbols, func(i, j int) bool {
		return allSymbols[i].Name < allSymbols[j].Name
	})
	var sb strings.Builder
	sb.WriteString(generatedTag + "\n")
	sb.WriteString(fmt.Sprintf("# Symbol Index\n\n%d key types and functions.\n\n", len(allSymbols)))
	sb.WriteString("| Symbol | Kind | Location |\n")
	sb.WriteString("|--------|------|----------|\n")
	for _, s := range allSymbols {
		sb.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", s.Name, s.Kind, s.Location))
	}
	md := sb.String()
	if err := os.WriteFile(filepath.Join(cfg.wikiRoot, "symbol-index.md"), []byte(md), 0644); err != nil {
		return 0, err
	}
	return len(allSymbols), writeHTMLPage(filepath.Join(cfg.wikiRoot, "symbol-index.html"), "Symbol Index", md, "", nil)
}

func writeChurn(cfg config, entries []churnEntry) error {
	if len(entries) == 0 {
		return nil
	}
	var sb strings.Builder
	sb.WriteString(generatedTag + "\n")
	sb.WriteString("# Recent Activity\n\nCommit frequency by directory over the last 90 days.\n\n")
	sb.WriteString("| Directory | Commits (90d) | Churn |\n")
	sb.WriteString("|-----------|---------------|-------|\n")
	for _, e := range entries {
		sb.WriteString(fmt.Sprintf("| %s | %d | %s |\n", e.Dir, e.Count, e.Level))
	}
	md := sb.String()
	if err := os.WriteFile(filepath.Join(cfg.wikiRoot, "churn.md"), []byte(md), 0644); err != nil {
		return err
	}
	return writeHTMLPage(filepath.Join(cfg.wikiRoot, "churn.html"), "Recent Activity", md, "", nil)
}

func writeRecipesFile(cfg config, content string) error {
	if content == "" {
		return nil
	}
	md := fmt.Sprintf("%s\n# Modification Recipes\n\nCommon change patterns derived from git history.\n\n%s\n", generatedTag, content)
	if err := os.WriteFile(filepath.Join(cfg.wikiRoot, "recipes.md"), []byte(md), 0644); err != nil {
		return err
	}
	return writeHTMLPage(filepath.Join(cfg.wikiRoot, "recipes.html"), "Modification Recipes", md, "", nil)
}

func writeTracesFile(cfg config, content string) error {
	if content == "" {
		return nil
	}
	md := fmt.Sprintf("%s\n# Entry Point Traces\n\nEnd-to-end execution flows through the codebase.\n\n%s\n", generatedTag, content)
	if err := os.WriteFile(filepath.Join(cfg.wikiRoot, "traces.md"), []byte(md), 0644); err != nil {
		return err
	}
	return writeHTMLPage(filepath.Join(cfg.wikiRoot, "traces.html"), "Entry Point Traces", md, "", nil)
}

// ---------------------------------------------------------------------------
// Wiki generation
// ---------------------------------------------------------------------------

func buildWiki(cfg config, dirs []string, summaries map[string]string, rootOverview string, artifacts wikiArtifacts) string {
	var sb strings.Builder
	sb.WriteString(generatedTag + "\n")
	sb.WriteString("# Codebase Wiki\n\n")

	// Project overview from root-level LLM call.
	if rootOverview != "" {
		sb.WriteString(rootOverview)
		sb.WriteString("\n\n")
	} else {
		sb.WriteString("Hierarchical documentation of the project source code.\n\n")
	}

	var topLevel []string
	for _, d := range dirs {
		if !strings.Contains(d, string(os.PathSeparator)) {
			topLevel = append(topLevel, d)
		}
	}
	sort.Strings(topLevel)

	// Annotated contents — each entry gets a one-line description.
	sb.WriteString("## Contents\n\n")
	for _, d := range topLevel {
		desc := ""
		if s, ok := summaries[d]; ok {
			desc = extractFirstSentence(s)
		}
		if desc != "" {
			sb.WriteString(fmt.Sprintf("- [%s/](./%s/SUMMARY.md) — %s\n", d, d, desc))
		} else {
			sb.WriteString(fmt.Sprintf("- [%s/](./%s/SUMMARY.md)\n", d, d))
		}
	}
	sb.WriteString("\n")

	// Root artifact links.
	if !cfg.noDepsGraph && artifacts.depsEdgeCount > 0 {
		sb.WriteString(fmt.Sprintf("## Dependency graph\n\n%d directories with dependency edges. [Full graph →](./deps-graph.md)\n\n", artifacts.depsEdgeCount))
	}
	if !cfg.noFileIndex && artifacts.fileCount > 0 {
		sb.WriteString(fmt.Sprintf("## File index\n\n%d source files across %d directories. [Full index →](./file-index.md)\n\n", artifacts.fileCount, artifacts.dirCount))
	}
	if !cfg.noSymbolIndex && artifacts.symbolCount > 0 {
		sb.WriteString(fmt.Sprintf("## Symbol index\n\n%d key types and functions. [Full index →](./symbol-index.md)\n\n", artifacts.symbolCount))
	}
	if !cfg.noChurn && artifacts.hasChurn {
		sb.WriteString("## Recent activity\n\nCommit frequency by directory (90 days). [Full analysis →](./churn.md)\n\n")
	}
	if !cfg.noRecipes && artifacts.hasRecipes {
		sb.WriteString("## Modification recipes\n\nCommon change patterns derived from git history. [Full recipes →](./recipes.md)\n\n")
	}
	if !cfg.noTraces && artifacts.hasTraces {
		sb.WriteString("## Entry point traces\n\nEnd-to-end execution flows through the codebase. [Full traces →](./traces.md)\n\n")
	}
	sb.WriteString("---\n\n")

	for _, d := range topLevel {
		sb.WriteString(fmt.Sprintf("## %s\n\n", d))
		if s, ok := summaries[d]; ok {
			lines := strings.Split(s, "\n")
			var content []string
			for _, l := range lines {
				if strings.HasPrefix(l, "<!-- ") || (strings.HasPrefix(l, "# ") && !strings.HasPrefix(l, "## ")) {
					continue
				}
				content = append(content, l)
			}
			sb.WriteString(strings.TrimSpace(strings.Join(content, "\n")))
			sb.WriteString("\n\n")
		}
		sb.WriteString(fmt.Sprintf("[Full details →](./%s/SUMMARY.md)\n\n---\n\n", d))
	}

	return sb.String()
}

// ---------------------------------------------------------------------------
// Progress output
// ---------------------------------------------------------------------------

func emitProgress(cfg config, ev progressEvent) {
	if !cfg.jsonProgress {
		return
	}
	data, _ := json.Marshal(ev)
	fmt.Fprintln(os.Stderr, string(data))
}

// ---------------------------------------------------------------------------
// LLM skill files
// ---------------------------------------------------------------------------

// wikiSection is the marker used to delimit the wikigen-managed block inside
// existing CLAUDE.md / AGENTS.md files.
const (
	wikiSectionStart = "<!-- wikigen:start -->"
	wikiSectionEnd   = "<!-- wikigen:end -->"
)

// writeSkillFiles writes wiki navigation instructions into CLAUDE.md and
// AGENTS.md in the repo root. If a file already exists (user-authored), the
// wiki section is appended or updated in place between marker comments. If
// the file doesn't exist, it is created with the full template.
func writeSkillFiles(cfg config) {
	// Compute wiki path relative to the repo root.
	wikiRel, err := filepath.Rel(cfg.repoRoot, filepath.Join(cfg.wikiRoot, "wiki.md"))
	if err != nil {
		wikiRel = filepath.Join(cfg.wikiRoot, "wiki.md") // fall back to absolute
	}

	for _, name := range []string{"templates/CLAUDE.md", "templates/AGENTS.md"} {
		data, err := skillTemplates.ReadFile(name)
		if err != nil {
			continue
		}

		// Replace placeholders with actual wiki paths.
		wikiDir := filepath.Dir(wikiRel)
		if wikiDir == "." {
			wikiDir = ""
		}
		section := strings.ReplaceAll(string(data), "{{WIKI_PATH}}", wikiRel)
		// When wiki is in repo root, {{WIKI_DIR}}/ should collapse to empty
		// so paths like "{{WIKI_DIR}}/cmd/SUMMARY.md" become "cmd/SUMMARY.md".
		if wikiDir == "" {
			section = strings.ReplaceAll(section, "{{WIKI_DIR}}/", "")
		} else {
			section = strings.ReplaceAll(section, "{{WIKI_DIR}}", wikiDir)
		}
		wrappedSection := fmt.Sprintf("%s\n%s\n%s", wikiSectionStart, strings.TrimSpace(section), wikiSectionEnd)

		outName := filepath.Base(name)
		outPath := filepath.Join(cfg.repoRoot, outName)

		existing, err := os.ReadFile(outPath)
		if err != nil {
			// File doesn't exist — create it with just our section.
			if err := os.WriteFile(outPath, []byte(wrappedSection+"\n"), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
			}
			continue
		}

		content := string(existing)
		startIdx := strings.Index(content, wikiSectionStart)
		endIdx := strings.Index(content, wikiSectionEnd)

		if startIdx >= 0 && endIdx >= 0 && endIdx > startIdx {
			// Replace existing wikigen section in place.
			updated := content[:startIdx] + wrappedSection + content[endIdx+len(wikiSectionEnd):]
			if err := os.WriteFile(outPath, []byte(updated), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
			}
		} else {
			// Append the wiki section to the existing file.
			separator := "\n\n"
			if strings.HasSuffix(content, "\n\n") {
				separator = ""
			} else if strings.HasSuffix(content, "\n") {
				separator = "\n"
			}
			updated := content + separator + wrappedSection + "\n"
			if err := os.WriteFile(outPath, []byte(updated), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Clean
// ---------------------------------------------------------------------------

func doClean(cfg config) {
	removed := 0
	filepath.Walk(cfg.wikiRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			return nil
		}
		name := info.Name()
		if name == "SUMMARY.md" || name == "SUMMARY.html" {
			if name == "SUMMARY.html" {
				os.Remove(path)
				fmt.Fprintf(os.Stderr, "Removed %s\n", path)
				removed++
			} else {
				data, err := os.ReadFile(path)
				if err == nil && strings.Contains(string(data), "Generated by wikigen") {
					os.Remove(path)
					fmt.Fprintf(os.Stderr, "Removed %s\n", path)
					removed++
				}
			}
		}
		return nil
	})

	for _, name := range []string{
		"wiki.md", "index.html",
		"deps-graph.md", "deps-graph.html",
		"file-index.md", "file-index.html",
		"symbol-index.md", "symbol-index.html",
		"recipes.md", "recipes.html",
		"traces.md", "traces.html",
		"churn.md", "churn.html",
	} {
		p := filepath.Join(cfg.wikiRoot, name)
		if data, err := os.ReadFile(p); err == nil && strings.Contains(string(data), "wikigen") {
			os.Remove(p)
			fmt.Fprintf(os.Stderr, "Removed %s\n", p)
			removed++
		}
	}

	// Remove wikigen section from skill files in the repo root.
	for _, name := range []string{"CLAUDE.md", "AGENTS.md"} {
		p := filepath.Join(cfg.repoRoot, name)
		data, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		content := string(data)
		startIdx := strings.Index(content, wikiSectionStart)
		endIdx := strings.Index(content, wikiSectionEnd)
		if startIdx < 0 || endIdx < 0 || endIdx <= startIdx {
			continue
		}
		// Remove the section and any surrounding blank lines.
		before := strings.TrimRight(content[:startIdx], "\n")
		after := strings.TrimLeft(content[endIdx+len(wikiSectionEnd):], "\n")
		cleaned := before
		if after != "" {
			if cleaned != "" {
				cleaned += "\n\n"
			}
			cleaned += after
		}
		if strings.TrimSpace(cleaned) == "" {
			// File was entirely the wikigen section — remove it.
			os.Remove(p)
			fmt.Fprintf(os.Stderr, "Removed %s\n", p)
		} else {
			if !strings.HasSuffix(cleaned, "\n") {
				cleaned += "\n"
			}
			os.WriteFile(p, []byte(cleaned), 0644)
			fmt.Fprintf(os.Stderr, "Removed wiki section from %s\n", p)
		}
		removed++
	}

	manifestPath := filepath.Join(cfg.wikiRoot, manifestFile)
	if err := os.Remove(manifestPath); err == nil {
		fmt.Fprintf(os.Stderr, "Removed %s\n", manifestPath)
		removed++
	}

	fmt.Fprintf(os.Stderr, "Cleaned %d generated files.\n", removed)
}
