package main

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/yuin/goldmark"
)

//go:embed templates/CLAUDE.md templates/AGENTS.md
var skillTemplates embed.FS

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const (
	maxFileBytes    = 100 * 1024 // skip files larger than 100 KB
	maxFileLines    = 500        // truncate to 500 lines for LLM input
	apiURL          = "https://api.anthropic.com/v1/messages"
	llmModel        = "claude-haiku-4-5-20251001"
	apiVersion      = "2023-06-01"
	generatedTag    = "<!-- Generated by wikigen. Do not edit manually. -->"
	manifestFile    = ".wikigen-manifest.json"
	manifestVersion = 1
)

// Default directory exclusions (by base name).
var defaultExcludes = []string{".claude", ".codex", "docs"}

// Lock / generated data files to skip.
var skipFiles = map[string]bool{
	"pnpm-lock.yaml":    true,
	"package-lock.json": true,
	"go.sum":            true,
}

// Extension → language label.
var extLang = map[string]string{
	".go":    "Go",
	".swift": "Swift",
	".ts":    "TypeScript",
	".tsx":   "TypeScript",
	".js":    "JavaScript",
	".jsx":   "JavaScript",
	".c":     "C",
	".h":     "C",
	".py":    "Python",
	".sh":    "Shell",
	".yaml":  "YAML",
	".yml":   "YAML",
	".toml":  "TOML",
	".json":  "JSON",
}

// Special filename prefixes/exact matches that map to a language.
var specialFiles = map[string]string{
	"Makefile":   "Make",
	"Dockerfile": "Docker",
}

// Regex for rewriting file links in LLM output.
var linkPattern = regexp.MustCompile(`\[([^\]]+)\]\(\./([^)]+)\)`)

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type config struct {
	repoRoot          string
	wikiRoot          string
	excludes          map[string]bool
	baseURL           string
	dryRun            bool
	clean             bool
	full              bool
	jsonProgress      bool
	apiKey            string
	noDefaultExcludes bool
}

type fileEntry struct {
	Name     string
	Language string
	Content  string
}

type dirBundle struct {
	Path           string
	Files          []fileEntry
	ChildSummaries []string
	ChildDirs      []string
}

// ---------------------------------------------------------------------------
// Manifest types
// ---------------------------------------------------------------------------

type manifestDirEntry struct {
	FilesHash   string            `json:"files_hash"`
	SummaryHash string            `json:"summary_hash"`
	Files       map[string]string `json:"files"`
}

type manifest struct {
	Version     int                         `json:"version"`
	Repo        string                      `json:"repo"`
	LastCommit  string                      `json:"last_commit"`
	GeneratedAt string                      `json:"generated_at"`
	Excludes    []string                    `json:"excludes"`
	Directories map[string]manifestDirEntry `json:"directories"`
}

// ---------------------------------------------------------------------------
// JSON progress event
// ---------------------------------------------------------------------------

type progressEvent struct {
	Event        string `json:"event"`
	Dir          string `json:"dir,omitempty"`
	Status       string `json:"status,omitempty"`
	FilesChanged int    `json:"files_changed,omitempty"`
	Message      string `json:"message,omitempty"`
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

func main() {
	cfg := parseArgs()

	if cfg.clean {
		doClean(cfg)
		return
	}

	if !cfg.dryRun && cfg.apiKey == "" {
		fmt.Fprintln(os.Stderr, "error: ANTHROPIC_API_KEY environment variable is not set")
		fmt.Fprintln(os.Stderr, "Set it or use --dry-run to test without API calls.")
		os.Exit(1)
	}

	// 1. Collect directories in post-order.
	dirs, err := collectDirs(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error walking directories: %v\n", err)
		os.Exit(1)
	}

	// 2. Load manifest and detect changes.
	oldManifest := loadManifest(cfg)
	forceFullScan := cfg.full || oldManifest == nil || oldManifest.Version != manifestVersion || !excludesMatch(oldManifest.Excludes, cfg.excludes)

	// Compute current hashes for all directories.
	currentHashes := computeAllHashes(cfg, dirs)

	// Determine dirty set.
	dirty := make(map[string]bool)
	if forceFullScan {
		for _, d := range dirs {
			dirty[d] = true
		}
		if !cfg.full && oldManifest != nil && oldManifest.Version != manifestVersion {
			emitProgress(cfg, progressEvent{Event: "info", Message: "Manifest version changed, forcing full scan"})
		}
		if !cfg.full && oldManifest != nil && !excludesMatch(oldManifest.Excludes, cfg.excludes) {
			emitProgress(cfg, progressEvent{Event: "info", Message: "Exclusion list changed, forcing full scan"})
		}
	} else {
		// Try git diff first, fall back to hash comparison.
		dirty = detectChangesGit(cfg, oldManifest, dirs)
		if dirty == nil {
			dirty = detectChangesHash(oldManifest, currentHashes, dirs)
		}
	}

	// Propagate dirty upward.
	propagateDirty(dirty, dirs)

	// Handle deleted directories.
	if oldManifest != nil {
		handleDeletedDirs(cfg, oldManifest, dirs, dirty)
	}

	// Check if anything needs work.
	dirtyCount := 0
	for _, d := range dirs {
		if dirty[d] {
			dirtyCount++
		}
	}
	if dirtyCount == 0 {
		emitProgress(cfg, progressEvent{Event: "done", Message: fmt.Sprintf("No changes detected (%d directories)", len(dirs))})
		os.Exit(0)
	}

	// 3. Create wiki output directory structure.
	if cfg.wikiRoot != cfg.repoRoot {
		os.MkdirAll(cfg.wikiRoot, 0755)
	}

	// 4. Process directories: summarize dirty ones, load existing for clean ones.
	summaries := make(map[string]string)
	newManifest := &manifest{
		Version:     manifestVersion,
		Repo:        cfg.repoRoot,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Excludes:    sortedExcludes(cfg.excludes),
		Directories: make(map[string]manifestDirEntry),
	}

	regenCount := 0
	skipCount := 0
	failCount := 0

	for _, rel := range dirs {
		if !dirty[rel] {
			// Load existing summary from wiki folder.
			existing := loadExistingSummary(cfg, rel)
			if existing != "" {
				summaries[rel] = existing
			}
			// Carry forward manifest entry.
			if oldManifest != nil {
				if entry, ok := oldManifest.Directories[rel]; ok {
					newManifest.Directories[rel] = entry
				}
			}
			// Ensure HTML exists even for skipped directories.
			if existing != "" && !cfg.dryRun {
				htmlPath := filepath.Join(cfg.wikiRoot, rel, "SUMMARY.html")
				if _, err := os.Stat(htmlPath); os.IsNotExist(err) {
					writeHTMLPage(htmlPath, filepath.Base(rel), existing, rel)
				}
			}
			emitProgress(cfg, progressEvent{Event: "skip", Dir: rel, Status: "unchanged"})
			skipCount++
			continue
		}

		bundle := buildBundle(cfg, rel, summaries)
		if len(bundle.Files) == 0 && len(bundle.ChildSummaries) == 0 {
			continue
		}

		nFiles := len(bundle.Files)
		nChildren := len(bundle.ChildSummaries)
		emitProgress(cfg, progressEvent{Event: "regenerate", Dir: rel, Status: "dirty", FilesChanged: nFiles})

		if !cfg.jsonProgress {
			fmt.Fprintf(os.Stderr, "Summarizing %s/ (%d files, %d children)...\n", rel, nFiles, nChildren)
		}

		if cfg.dryRun {
			summaries[rel] = fmt.Sprintf("(dry-run) %s: %d files, %d children", rel, nFiles, nChildren)
			continue
		}

		summary, err := summarize(cfg.apiKey, bundle)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  warning: summarization failed for %s: %v\n", rel, err)
			summary = fmt.Sprintf("Summary generation failed for `%s`.", rel)
			failCount++
		}

		// Post-process links.
		summary = rewriteLinks(cfg, rel, summary)

		// Strip any leading H1 the LLM may have generated to avoid duplicates.
		summary = stripLeadingH1(summary)

		md := fmt.Sprintf("%s\n# %s\n\n%s\n", generatedTag, filepath.Base(rel), summary)
		summaries[rel] = md

		// Write SUMMARY.md to wiki folder.
		outDir := filepath.Join(cfg.wikiRoot, rel)
		os.MkdirAll(outDir, 0755)
		outPath := filepath.Join(outDir, "SUMMARY.md")
		if err := os.WriteFile(outPath, []byte(md), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
		}

		// Write SUMMARY.html alongside the markdown.
		htmlPath := filepath.Join(outDir, "SUMMARY.html")
		if err := writeHTMLPage(htmlPath, filepath.Base(rel), md, rel); err != nil {
			fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", htmlPath, err)
		}

		// Update manifest entry.
		if ch, ok := currentHashes[rel]; ok {
			ch.SummaryHash = hashString(md)
			newManifest.Directories[rel] = ch
		}
		regenCount++
	}

	// 5. Generate root overview and wiki.md.
	if !cfg.dryRun {
		// Collect top-level dirs for root overview.
		var topLevel []string
		for _, d := range dirs {
			if !strings.Contains(d, string(os.PathSeparator)) {
				topLevel = append(topLevel, d)
			}
		}
		sort.Strings(topLevel)

		emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "Generating project overview"})
		if !cfg.jsonProgress {
			fmt.Fprintln(os.Stderr, "Generating project overview...")
		}
		rootOverview, err := summarizeRoot(cfg.apiKey, topLevel, summaries)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  warning: root overview generation failed: %v\n", err)
			rootOverview = ""
		}

		emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "Generating wiki.md"})
		if !cfg.jsonProgress {
			fmt.Fprintln(os.Stderr, "Generating wiki.md...")
		}
		wiki := buildWiki(cfg, dirs, summaries, rootOverview)
		wikiPath := filepath.Join(cfg.wikiRoot, "wiki.md")
		if err := os.WriteFile(wikiPath, []byte(wiki), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error writing wiki.md: %v\n", err)
			os.Exit(1)
		}

		// Write index.html alongside wiki.md.
		indexPath := filepath.Join(cfg.wikiRoot, "index.html")
		if err := writeHTMLPage(indexPath, "Codebase Wiki", wiki, ""); err != nil {
			fmt.Fprintf(os.Stderr, "error writing index.html: %v\n", err)
		}

		// Write LLM skill files (CLAUDE.md, AGENTS.md) into the wiki output.
		writeSkillFiles(cfg)
	} else {
		emitProgress(cfg, progressEvent{Event: "write", Dir: ".", Message: "(dry-run) Would write wiki.md"})
		if !cfg.jsonProgress {
			fmt.Fprintln(os.Stderr, "(dry-run) Would write wiki.md")
		}
	}

	// 6. Save manifest.
	if !cfg.dryRun {
		// Get current git HEAD.
		newManifest.LastCommit = getGitHead(cfg.repoRoot)
		saveManifest(cfg, newManifest)
	}

	// 7. Print stats.
	total := len(dirs)
	msg := fmt.Sprintf("Regenerated %d/%d directories (%d skipped)", regenCount, total, skipCount)
	if failCount > 0 {
		msg += fmt.Sprintf(", %d failed", failCount)
	}
	emitProgress(cfg, progressEvent{Event: "done", Message: msg})
	if !cfg.jsonProgress {
		fmt.Fprintln(os.Stderr, msg)
	}

	if failCount > 0 {
		os.Exit(2) // partial failure
	}
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

func parseArgs() config {
	cfg := config{
		excludes: make(map[string]bool),
	}
	var userExcludes []string
	args := os.Args[1:]

	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--dry-run":
			cfg.dryRun = true
		case a == "--clean":
			cfg.clean = true
		case a == "--full":
			cfg.full = true
		case a == "--json":
			cfg.jsonProgress = true
		case a == "--no-default-excludes":
			cfg.noDefaultExcludes = true
		case a == "--help" || a == "-h":
			printUsage()
			os.Exit(0)
		case a == "--output" && i+1 < len(args):
			i++
			cfg.wikiRoot = args[i]
		case a == "--exclude" && i+1 < len(args):
			i++
			userExcludes = append(userExcludes, args[i])
		case a == "--base-url" && i+1 < len(args):
			i++
			cfg.baseURL = strings.TrimRight(args[i], "/")
		case strings.HasPrefix(a, "-"):
			fmt.Fprintf(os.Stderr, "unknown flag: %s\n", a)
			printUsage()
			os.Exit(1)
		default:
			cfg.repoRoot = a
		}
	}

	if cfg.repoRoot == "" {
		cfg.repoRoot = "."
	}
	cfg.repoRoot, _ = filepath.Abs(cfg.repoRoot)

	if cfg.wikiRoot == "" {
		cfg.wikiRoot = cfg.repoRoot
	} else {
		cfg.wikiRoot, _ = filepath.Abs(cfg.wikiRoot)
	}

	// Build exclusion set.
	cfg.excludes[".git"] = true // always exclude .git
	if !cfg.noDefaultExcludes {
		for _, d := range defaultExcludes {
			cfg.excludes[d] = true
		}
	}
	for _, d := range userExcludes {
		cfg.excludes[d] = true
	}

	cfg.apiKey = os.Getenv("ANTHROPIC_API_KEY")

	return cfg
}

func printUsage() {
	fmt.Fprintln(os.Stderr, `Usage: wikigen [flags] <repo>

Generates hierarchical markdown documentation for a codebase.

Flags:
  --output <dir>       Wiki output directory (default: in-place in repo)
  --exclude <pattern>  Exclude directory by base name (repeatable)
  --no-default-excludes  Clear default exclusions (only .git remains)
  --base-url <url>     URL prefix for source file links (e.g. https://github.com/org/repo/blob/main)
  --full               Force full regeneration (ignore manifest)
  --json               Emit line-delimited JSON progress events on stderr
  --dry-run            Show what would be summarized without calling the API
  --clean              Remove all generated files and manifest from wiki folder
  --help               Show this help message`)
}

// ---------------------------------------------------------------------------
// Directory collection (post-order)
// ---------------------------------------------------------------------------

func collectDirs(cfg config) ([]string, error) {
	var dirs []string
	err := filepath.Walk(cfg.repoRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() {
			return nil
		}
		base := info.Name()
		if path != cfg.repoRoot && (strings.HasPrefix(base, ".") || cfg.excludes[base]) {
			return filepath.SkipDir
		}
		rel, _ := filepath.Rel(cfg.repoRoot, path)
		if rel == "." {
			return nil
		}
		dirs = append(dirs, rel)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(dirs, func(i, j int) bool {
		di := strings.Count(dirs[i], string(os.PathSeparator))
		dj := strings.Count(dirs[j], string(os.PathSeparator))
		if di != dj {
			return di > dj
		}
		return dirs[i] < dirs[j]
	})
	return dirs, nil
}

// ---------------------------------------------------------------------------
// Hashing
// ---------------------------------------------------------------------------

func hashBytes(data []byte) string {
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:])
}

func hashString(s string) string {
	return hashBytes([]byte(s))
}

func computeAllHashes(cfg config, dirs []string) map[string]manifestDirEntry {
	result := make(map[string]manifestDirEntry)
	for _, rel := range dirs {
		abs := filepath.Join(cfg.repoRoot, rel)
		entries, err := os.ReadDir(abs)
		if err != nil {
			continue
		}
		fileHashes := make(map[string]string)
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			name := e.Name()
			if !isEligibleFile(name) {
				continue
			}
			content, err := readFileContent(filepath.Join(abs, name))
			if err != nil || content == "" {
				continue
			}
			fileHashes[name] = hashString(content)
		}
		// Compute directory-level hash from sorted file hashes.
		var pairs []string
		for name, h := range fileHashes {
			pairs = append(pairs, name+":"+h)
		}
		sort.Strings(pairs)
		dirHash := hashString(strings.Join(pairs, "\n"))

		result[rel] = manifestDirEntry{
			FilesHash: dirHash,
			Files:     fileHashes,
		}
	}
	return result
}

// ---------------------------------------------------------------------------
// Manifest load/save
// ---------------------------------------------------------------------------

func loadManifest(cfg config) *manifest {
	path := filepath.Join(cfg.wikiRoot, manifestFile)
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		fmt.Fprintf(os.Stderr, "warning: corrupt manifest, will regenerate all: %v\n", err)
		return nil
	}
	return &m
}

func saveManifest(cfg config, m *manifest) {
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error marshaling manifest: %v\n", err)
		return
	}
	path := filepath.Join(cfg.wikiRoot, manifestFile)
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, data, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing manifest: %v\n", err)
		return
	}
	if err := os.Rename(tmpPath, path); err != nil {
		fmt.Fprintf(os.Stderr, "error renaming manifest: %v\n", err)
	}
}

func excludesMatch(a []string, b map[string]bool) bool {
	if len(a) != len(b) {
		return false
	}
	set := make(map[string]bool)
	for _, s := range a {
		set[s] = true
	}
	for k := range b {
		if !set[k] {
			return false
		}
	}
	return true
}

func sortedExcludes(m map[string]bool) []string {
	var s []string
	for k := range m {
		s = append(s, k)
	}
	sort.Strings(s)
	return s
}

// ---------------------------------------------------------------------------
// Change detection: git
// ---------------------------------------------------------------------------

func getGitHead(repoRoot string) string {
	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func isGitRepo(repoRoot string) bool {
	info, err := os.Stat(filepath.Join(repoRoot, ".git"))
	return err == nil && info.IsDir()
}

func detectChangesGit(cfg config, old *manifest, dirs []string) map[string]bool {
	if !isGitRepo(cfg.repoRoot) || old.LastCommit == "" {
		return nil // fall back to hash
	}

	currentHead := getGitHead(cfg.repoRoot)
	if currentHead == "" {
		return nil
	}
	if currentHead == old.LastCommit {
		// Same commit — no changes from git's perspective.
		// Still need to check for new/removed dirs via hash comparison.
		return detectChangesHash(old, computeAllHashes(cfg, dirs), dirs)
	}

	cmd := exec.Command("git", "diff", "--name-only", old.LastCommit, currentHead)
	cmd.Dir = cfg.repoRoot
	out, err := cmd.Output()
	if err != nil {
		emitProgress(cfg, progressEvent{Event: "info", Message: "git diff failed, falling back to hash comparison"})
		return nil
	}

	dirty := make(map[string]bool)
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	dirSet := make(map[string]bool)
	for _, d := range dirs {
		dirSet[d] = true
	}

	for _, line := range lines {
		if line == "" {
			continue
		}
		dir := filepath.Dir(line)
		// Walk up to find the first eligible directory.
		for dir != "." && dir != "" {
			if dirSet[dir] {
				dirty[dir] = true
				break
			}
			dir = filepath.Dir(dir)
		}
	}

	// Also check for new directories (not in manifest).
	for _, d := range dirs {
		if _, exists := old.Directories[d]; !exists {
			dirty[d] = true
		}
	}

	return dirty
}

// ---------------------------------------------------------------------------
// Change detection: hash fallback
// ---------------------------------------------------------------------------

func detectChangesHash(old *manifest, current map[string]manifestDirEntry, dirs []string) map[string]bool {
	dirty := make(map[string]bool)
	for _, d := range dirs {
		cur, hasCur := current[d]
		oldEntry, hasOld := old.Directories[d]
		if !hasOld {
			dirty[d] = true // new directory
			continue
		}
		if !hasCur {
			continue
		}
		if cur.FilesHash != oldEntry.FilesHash {
			dirty[d] = true
		}
	}
	return dirty
}

// ---------------------------------------------------------------------------
// Dirty propagation
// ---------------------------------------------------------------------------

func propagateDirty(dirty map[string]bool, dirs []string) {
	// Process in reverse (shallowest first) to propagate upward.
	for i := len(dirs) - 1; i >= 0; i-- {
		d := dirs[i]
		if !dirty[d] {
			continue
		}
		parent := filepath.Dir(d)
		for parent != "." && parent != "" {
			dirty[parent] = true
			parent = filepath.Dir(parent)
		}
	}
}

// ---------------------------------------------------------------------------
// Deleted directory handling
// ---------------------------------------------------------------------------

func handleDeletedDirs(cfg config, old *manifest, dirs []string, dirty map[string]bool) {
	currentSet := make(map[string]bool)
	for _, d := range dirs {
		currentSet[d] = true
	}
	for d := range old.Directories {
		if !currentSet[d] {
			// Directory was removed from repo.
			summaryPath := filepath.Join(cfg.wikiRoot, d, "SUMMARY.md")
			if err := os.Remove(summaryPath); err == nil {
				emitProgress(cfg, progressEvent{Event: "delete", Dir: d, Message: "Removed deleted directory summary"})
			}
			// Mark parent as dirty.
			parent := filepath.Dir(d)
			if parent != "." {
				dirty[parent] = true
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Bundle building
// ---------------------------------------------------------------------------

func buildBundle(cfg config, rel string, summaries map[string]string) dirBundle {
	abs := filepath.Join(cfg.repoRoot, rel)
	entries, _ := os.ReadDir(abs)

	b := dirBundle{Path: rel}

	for _, e := range entries {
		if e.IsDir() {
			childRel := filepath.Join(rel, e.Name())
			if s, ok := summaries[childRel]; ok {
				b.ChildSummaries = append(b.ChildSummaries, s)
				b.ChildDirs = append(b.ChildDirs, e.Name())
			}
			continue
		}
		name := e.Name()
		if !isEligibleFile(name) {
			continue
		}
		lang := detectLanguage(name)
		if lang == "" {
			continue
		}
		content, err := readFileContent(filepath.Join(abs, name))
		if err != nil || content == "" {
			continue
		}
		b.Files = append(b.Files, fileEntry{Name: name, Language: lang, Content: content})
	}
	sort.Slice(b.Files, func(i, j int) bool {
		return b.Files[i].Name < b.Files[j].Name
	})
	return b
}

func isEligibleFile(name string) bool {
	if skipFiles[name] || name == "SUMMARY.md" || name == manifestFile {
		return false
	}
	if detectLanguage(name) == "" {
		return false
	}
	return true
}

func detectLanguage(name string) string {
	for prefix, lang := range specialFiles {
		if name == prefix || strings.HasPrefix(name, prefix+".") {
			return lang
		}
	}
	ext := filepath.Ext(name)
	return extLang[ext]
}

func readFileContent(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return "", err
	}
	if info.Size() > maxFileBytes {
		return "", nil
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}

	check := data
	if len(check) > 512 {
		check = check[:512]
	}
	if bytes.ContainsRune(check, 0) {
		return "", nil
	}

	header := string(check)
	if strings.Contains(header, "Code generated") || strings.Contains(header, "DO NOT EDIT") {
		return "", nil
	}

	lines := strings.SplitN(string(data), "\n", maxFileLines+1)
	if len(lines) > maxFileLines {
		lines = lines[:maxFileLines]
		lines = append(lines, fmt.Sprintf("\n... (truncated at %d lines)", maxFileLines))
	}
	return strings.Join(lines, "\n"), nil
}

// ---------------------------------------------------------------------------
// Load existing summary from wiki folder
// ---------------------------------------------------------------------------

func loadExistingSummary(cfg config, rel string) string {
	path := filepath.Join(cfg.wikiRoot, rel, "SUMMARY.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

// ---------------------------------------------------------------------------
// Claude API summarization
// ---------------------------------------------------------------------------

type apiMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type apiRequest struct {
	Model     string       `json:"model"`
	MaxTokens int          `json:"max_tokens"`
	System    string       `json:"system"`
	Messages  []apiMessage `json:"messages"`
}

type apiContentBlock struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

type apiResponse struct {
	Content []apiContentBlock `json:"content"`
	Error   *struct {
		Message string `json:"message"`
	} `json:"error"`
}

func summarize(apiKey string, b dirBundle) (string, error) {
	prompt := buildPrompt(b)

	reqBody := apiRequest{
		Model:     llmModel,
		MaxTokens: 1024,
		System: `You are writing navigation documentation for an LLM that will use this wiki to find relevant code for a given task. The LLM reads the wiki top-down, so each summary must help it decide which files or subdirectories to drill into.

Write a concise markdown summary following this structure:

1. **Overview** (1-2 sentences): What this directory is responsible for. State its role in the larger system.
2. **Key files**: Bullet list with relative links and one-line descriptions: - [filename](./filename) — description
3. **Key types/functions**: The most important exported types, functions, or interfaces.
4. **When to look here**: A bullet list of task descriptions that would lead an LLM to this directory. For example: "Modifying how Cedar policies are parsed", "Adding a new CLI subcommand", "Changing container network rules". Be specific to what the code actually does.
5. **Child directories** (if any): For each child, a bullet with a one-line description of what it owns and what tasks would require looking there.

Keep it concise and accurate. Do not invent functionality not present in the code. Use relative file links.`,
		Messages: []apiMessage{
			{Role: "user", Content: prompt},
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}

	req, err := http.NewRequest("POST", apiURL, bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", apiVersion)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("API call failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode != 200 {
		return "", fmt.Errorf("API returned %d: %s", resp.StatusCode, string(respBody))
	}

	var apiResp apiResponse
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if apiResp.Error != nil {
		return "", fmt.Errorf("API error: %s", apiResp.Error.Message)
	}

	var texts []string
	for _, block := range apiResp.Content {
		if block.Type == "text" {
			texts = append(texts, block.Text)
		}
	}
	return strings.Join(texts, "\n"), nil
}

func buildPrompt(b dirBundle) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Directory: `%s`\n\n", b.Path))

	if len(b.Files) > 0 {
		sb.WriteString("## Source files in this directory\n\n")
		for _, f := range b.Files {
			sb.WriteString(fmt.Sprintf("### %s (%s)\n```%s\n%s\n```\n\n", f.Name, f.Language, strings.ToLower(f.Language), f.Content))
		}
	}

	if len(b.ChildSummaries) > 0 {
		sb.WriteString("## Child directory summaries\n\n")
		for i, cs := range b.ChildSummaries {
			if i < len(b.ChildDirs) {
				sb.WriteString(fmt.Sprintf("### Child: %s/\n%s\n\n", b.ChildDirs[i], cs))
			}
		}
	}

	return sb.String()
}

// ---------------------------------------------------------------------------
// Link rewriting
// ---------------------------------------------------------------------------

func rewriteLinks(cfg config, dirRel string, summary string) string {
	if cfg.baseURL != "" {
		return linkPattern.ReplaceAllStringFunc(summary, func(match string) string {
			parts := linkPattern.FindStringSubmatch(match)
			if len(parts) != 3 {
				return match
			}
			label, file := parts[1], parts[2]
			return fmt.Sprintf("[%s](%s/%s/%s)", label, cfg.baseURL, dirRel, file)
		})
	}
	// No base URL: replace links with inline code.
	return linkPattern.ReplaceAllStringFunc(summary, func(match string) string {
		parts := linkPattern.FindStringSubmatch(match)
		if len(parts) != 3 {
			return match
		}
		return "`" + parts[1] + "`"
	})
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// stripLeadingH1 removes a leading "# ..." line from LLM output so we don't
// duplicate the header we add ourselves.
func stripLeadingH1(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "# ") {
		if idx := strings.Index(s, "\n"); idx >= 0 {
			return strings.TrimSpace(s[idx+1:])
		}
		return "" // entire string was a single H1
	}
	return s
}

// extractFirstSentence pulls the first non-empty, non-heading line from a
// summary and returns it (stripped of markdown formatting) as a one-line
// description suitable for a table-of-contents entry.
func extractFirstSentence(summary string) string {
	for _, line := range strings.Split(summary, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "<!--") || strings.HasPrefix(line, "---") {
			continue
		}
		// Strip bold/italic markers and leading list markers.
		line = strings.TrimLeft(line, "- *_")
		line = strings.TrimRight(line, " *_")
		// Truncate at first period if present.
		if idx := strings.Index(line, ". "); idx > 0 && idx < 200 {
			line = line[:idx+1]
		}
		if len(line) > 200 {
			line = line[:197] + "..."
		}
		return line
	}
	return ""
}

// ---------------------------------------------------------------------------
// HTML generation
// ---------------------------------------------------------------------------

var htmlTemplate = template.Must(template.New("page").Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}}</title>
<style>
  :root { --bg: #fff; --fg: #1a1a1a; --muted: #6b7280; --border: #e5e7eb; --link: #2563eb; --code-bg: #f3f4f6; --nav-bg: #f9fafb; }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #111; --fg: #e5e5e5; --muted: #9ca3af; --border: #333; --link: #60a5fa; --code-bg: #1e1e1e; --nav-bg: #1a1a1a; }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg); color: var(--fg); line-height: 1.6; max-width: 52rem; margin: 0 auto; padding: 2rem 1.5rem; }
  nav.breadcrumb { font-size: 0.85rem; color: var(--muted); margin-bottom: 1.5rem; padding: 0.5rem 0.75rem; background: var(--nav-bg); border-radius: 6px; }
  nav.breadcrumb a { color: var(--link); text-decoration: none; }
  nav.breadcrumb a:hover { text-decoration: underline; }
  h1 { font-size: 1.75rem; margin-bottom: 1rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }
  h2 { font-size: 1.35rem; margin-top: 2rem; margin-bottom: 0.75rem; }
  h3 { font-size: 1.1rem; margin-top: 1.5rem; margin-bottom: 0.5rem; }
  p { margin-bottom: 0.75rem; }
  a { color: var(--link); text-decoration: none; }
  a:hover { text-decoration: underline; }
  ul, ol { margin: 0.5rem 0 1rem 1.5rem; }
  li { margin-bottom: 0.25rem; }
  code { font-family: "SF Mono", "Fira Code", Menlo, monospace; font-size: 0.88em; background: var(--code-bg); padding: 0.15em 0.35em; border-radius: 4px; }
  pre { background: var(--code-bg); padding: 1rem; border-radius: 6px; overflow-x: auto; margin: 1rem 0; }
  pre code { background: none; padding: 0; font-size: 0.85em; }
  hr { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
  strong { font-weight: 600; }
  .generated { font-size: 0.75rem; color: var(--muted); text-align: center; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); }
</style>
</head>
<body>
{{if .Breadcrumb}}<nav class="breadcrumb">{{.Breadcrumb}}</nav>{{end}}
{{.Body}}
<div class="generated">Generated by wikigen</div>
</body>
</html>
`))

type htmlPage struct {
	Title      string
	Breadcrumb template.HTML
	Body       template.HTML
}

// markdownToHTML converts markdown text to an HTML body fragment.
func markdownToHTML(md string) string {
	// Strip the wikigen comment tag before converting.
	md = strings.ReplaceAll(md, generatedTag, "")
	var buf bytes.Buffer
	if err := goldmark.Convert([]byte(md), &buf); err != nil {
		return "<p>Error rendering markdown.</p>"
	}
	return buf.String()
}

// rewriteMDLinksToHTML rewrites .md hrefs to .html in the HTML output so
// navigation works in a browser.
var mdLinkInHTML = regexp.MustCompile(`href="([^"]*?)\.md"`)

func rewriteHTMLLinks(html string) string {
	return mdLinkInHTML.ReplaceAllString(html, `href="$1.html"`)
}

// buildBreadcrumb creates an HTML breadcrumb trail for a directory path.
// rel is relative to the wiki root (e.g., "internal/lsm").
func buildBreadcrumb(rel string) template.HTML {
	if rel == "" || rel == "." {
		return ""
	}
	parts := strings.Split(rel, string(os.PathSeparator))
	var crumbs []string
	// Link to root wiki.
	depth := len(parts)
	rootHref := strings.Repeat("../", depth) + "index.html"
	crumbs = append(crumbs, fmt.Sprintf(`<a href="%s">Wiki</a>`, rootHref))
	// Intermediate dirs.
	for i, p := range parts {
		if i == len(parts)-1 {
			crumbs = append(crumbs, p)
		} else {
			ups := len(parts) - i - 1
			href := strings.Repeat("../", ups) + "SUMMARY.html"
			crumbs = append(crumbs, fmt.Sprintf(`<a href="%s">%s</a>`, href, p))
		}
	}
	return template.HTML(strings.Join(crumbs, " / "))
}

// writeHTMLPage renders a markdown string as a styled HTML page.
func writeHTMLPage(outPath, title, mdContent, rel string) error {
	body := markdownToHTML(mdContent)
	body = rewriteHTMLLinks(body)

	page := htmlPage{
		Title:      title + " — Codebase Wiki",
		Breadcrumb: buildBreadcrumb(rel),
		Body:       template.HTML(body),
	}

	var buf bytes.Buffer
	if err := htmlTemplate.Execute(&buf, page); err != nil {
		return fmt.Errorf("render HTML template: %w", err)
	}
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

// ---------------------------------------------------------------------------
// Root-level project summary
// ---------------------------------------------------------------------------

func summarizeRoot(apiKey string, topDirs []string, summaries map[string]string) (string, error) {
	var sb strings.Builder
	sb.WriteString("Generate a project-level overview for an LLM that will use this wiki to navigate the codebase.\n\n")
	sb.WriteString("## Top-level directory summaries\n\n")
	for _, d := range topDirs {
		if s, ok := summaries[d]; ok {
			sb.WriteString(fmt.Sprintf("### %s/\n%s\n\n", d, s))
		}
	}

	reqBody := apiRequest{
		Model:     llmModel,
		MaxTokens: 1024,
		System: `You are writing the root page of a codebase wiki that an LLM will use to navigate code for tasks.

Given summaries of all top-level directories, produce:

1. **Project overview** (2-3 sentences): What the project is and does.
2. **Architecture snapshot** (3-5 sentences): How the major pieces connect.
3. **Navigation guide**: A bullet list mapping task categories to directories. For example:
   - "To modify CLI commands → cmd/"
   - "To change policy enforcement → internal/lsm/, internal/transpiler/"
   - "To update the web UI → controlui/"

Be specific and accurate. Do not add a Contents listing — that will be generated separately.`,
		Messages: []apiMessage{
			{Role: "user", Content: sb.String()},
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}

	req, err := http.NewRequest("POST", apiURL, bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", apiVersion)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("API call failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode != 200 {
		return "", fmt.Errorf("API returned %d: %s", resp.StatusCode, string(respBody))
	}

	var apiResp apiResponse
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if apiResp.Error != nil {
		return "", fmt.Errorf("API error: %s", apiResp.Error.Message)
	}

	var texts []string
	for _, block := range apiResp.Content {
		if block.Type == "text" {
			texts = append(texts, block.Text)
		}
	}
	return strings.Join(texts, "\n"), nil
}

// ---------------------------------------------------------------------------
// Wiki generation
// ---------------------------------------------------------------------------

func buildWiki(cfg config, dirs []string, summaries map[string]string, rootOverview string) string {
	var sb strings.Builder
	sb.WriteString(generatedTag + "\n")
	sb.WriteString("# Codebase Wiki\n\n")

	// Project overview from root-level LLM call.
	if rootOverview != "" {
		sb.WriteString(rootOverview)
		sb.WriteString("\n\n")
	} else {
		sb.WriteString("Hierarchical documentation of the project source code.\n\n")
	}

	var topLevel []string
	for _, d := range dirs {
		if !strings.Contains(d, string(os.PathSeparator)) {
			topLevel = append(topLevel, d)
		}
	}
	sort.Strings(topLevel)

	// Annotated contents — each entry gets a one-line description.
	sb.WriteString("## Contents\n\n")
	for _, d := range topLevel {
		desc := ""
		if s, ok := summaries[d]; ok {
			desc = extractFirstSentence(s)
		}
		if desc != "" {
			sb.WriteString(fmt.Sprintf("- [%s/](./%s/SUMMARY.md) — %s\n", d, d, desc))
		} else {
			sb.WriteString(fmt.Sprintf("- [%s/](./%s/SUMMARY.md)\n", d, d))
		}
	}
	sb.WriteString("\n---\n\n")

	for _, d := range topLevel {
		sb.WriteString(fmt.Sprintf("## %s\n\n", d))
		if s, ok := summaries[d]; ok {
			lines := strings.Split(s, "\n")
			var content []string
			for _, l := range lines {
				if strings.HasPrefix(l, "<!-- ") || (strings.HasPrefix(l, "# ") && !strings.HasPrefix(l, "## ")) {
					continue
				}
				content = append(content, l)
			}
			sb.WriteString(strings.TrimSpace(strings.Join(content, "\n")))
			sb.WriteString("\n\n")
		}
		sb.WriteString(fmt.Sprintf("[Full details →](./%s/SUMMARY.md)\n\n---\n\n", d))
	}

	return sb.String()
}

// ---------------------------------------------------------------------------
// Progress output
// ---------------------------------------------------------------------------

func emitProgress(cfg config, ev progressEvent) {
	if !cfg.jsonProgress {
		return
	}
	data, _ := json.Marshal(ev)
	fmt.Fprintln(os.Stderr, string(data))
}

// ---------------------------------------------------------------------------
// LLM skill files
// ---------------------------------------------------------------------------

// wikiSection is the marker used to delimit the wikigen-managed block inside
// existing CLAUDE.md / AGENTS.md files.
const (
	wikiSectionStart = "<!-- wikigen:start -->"
	wikiSectionEnd   = "<!-- wikigen:end -->"
)

// writeSkillFiles writes wiki navigation instructions into CLAUDE.md and
// AGENTS.md in the repo root. If a file already exists (user-authored), the
// wiki section is appended or updated in place between marker comments. If
// the file doesn't exist, it is created with the full template.
func writeSkillFiles(cfg config) {
	// Compute wiki path relative to the repo root.
	wikiRel, err := filepath.Rel(cfg.repoRoot, filepath.Join(cfg.wikiRoot, "wiki.md"))
	if err != nil {
		wikiRel = filepath.Join(cfg.wikiRoot, "wiki.md") // fall back to absolute
	}

	for _, name := range []string{"templates/CLAUDE.md", "templates/AGENTS.md"} {
		data, err := skillTemplates.ReadFile(name)
		if err != nil {
			continue
		}

		// Replace the placeholder with the actual wiki path.
		section := strings.ReplaceAll(string(data), "{{WIKI_PATH}}", wikiRel)
		wrappedSection := fmt.Sprintf("%s\n%s\n%s", wikiSectionStart, strings.TrimSpace(section), wikiSectionEnd)

		outName := filepath.Base(name)
		outPath := filepath.Join(cfg.repoRoot, outName)

		existing, err := os.ReadFile(outPath)
		if err != nil {
			// File doesn't exist — create it with just our section.
			if err := os.WriteFile(outPath, []byte(wrappedSection+"\n"), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
			}
			continue
		}

		content := string(existing)
		startIdx := strings.Index(content, wikiSectionStart)
		endIdx := strings.Index(content, wikiSectionEnd)

		if startIdx >= 0 && endIdx >= 0 && endIdx > startIdx {
			// Replace existing wikigen section in place.
			updated := content[:startIdx] + wrappedSection + content[endIdx+len(wikiSectionEnd):]
			if err := os.WriteFile(outPath, []byte(updated), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
			}
		} else {
			// Append the wiki section to the existing file.
			separator := "\n\n"
			if strings.HasSuffix(content, "\n\n") {
				separator = ""
			} else if strings.HasSuffix(content, "\n") {
				separator = "\n"
			}
			updated := content + separator + wrappedSection + "\n"
			if err := os.WriteFile(outPath, []byte(updated), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "  error writing %s: %v\n", outPath, err)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Clean
// ---------------------------------------------------------------------------

func doClean(cfg config) {
	removed := 0
	filepath.Walk(cfg.wikiRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			return nil
		}
		name := info.Name()
		if name == "SUMMARY.md" || name == "SUMMARY.html" {
			if name == "SUMMARY.html" {
				os.Remove(path)
				fmt.Fprintf(os.Stderr, "Removed %s\n", path)
				removed++
			} else {
				data, err := os.ReadFile(path)
				if err == nil && strings.Contains(string(data), "Generated by wikigen") {
					os.Remove(path)
					fmt.Fprintf(os.Stderr, "Removed %s\n", path)
					removed++
				}
			}
		}
		return nil
	})

	for _, name := range []string{"wiki.md", "index.html"} {
		p := filepath.Join(cfg.wikiRoot, name)
		if data, err := os.ReadFile(p); err == nil && strings.Contains(string(data), "wikigen") {
			os.Remove(p)
			fmt.Fprintf(os.Stderr, "Removed %s\n", p)
			removed++
		}
	}

	// Remove wikigen section from skill files in the repo root.
	for _, name := range []string{"CLAUDE.md", "AGENTS.md"} {
		p := filepath.Join(cfg.repoRoot, name)
		data, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		content := string(data)
		startIdx := strings.Index(content, wikiSectionStart)
		endIdx := strings.Index(content, wikiSectionEnd)
		if startIdx < 0 || endIdx < 0 || endIdx <= startIdx {
			continue
		}
		// Remove the section and any surrounding blank lines.
		before := strings.TrimRight(content[:startIdx], "\n")
		after := strings.TrimLeft(content[endIdx+len(wikiSectionEnd):], "\n")
		cleaned := before
		if after != "" {
			if cleaned != "" {
				cleaned += "\n\n"
			}
			cleaned += after
		}
		if strings.TrimSpace(cleaned) == "" {
			// File was entirely the wikigen section — remove it.
			os.Remove(p)
			fmt.Fprintf(os.Stderr, "Removed %s\n", p)
		} else {
			if !strings.HasSuffix(cleaned, "\n") {
				cleaned += "\n"
			}
			os.WriteFile(p, []byte(cleaned), 0644)
			fmt.Fprintf(os.Stderr, "Removed wiki section from %s\n", p)
		}
		removed++
	}

	manifestPath := filepath.Join(cfg.wikiRoot, manifestFile)
	if err := os.Remove(manifestPath); err == nil {
		fmt.Fprintf(os.Stderr, "Removed %s\n", manifestPath)
		removed++
	}

	fmt.Fprintf(os.Stderr, "Cleaned %d generated files.\n", removed)
}
